/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EscrowConditions {
  export type ConditionStruct = {
    conditionType: BigNumberish;
    oracle: AddressLike;
    parameters: BytesLike;
    threshold: BigNumberish;
    apiEndpoint: string;
    isMet: boolean;
    metAt: BigNumberish;
  };

  export type ConditionStructOutput = [
    conditionType: bigint,
    oracle: string,
    parameters: string,
    threshold: bigint,
    apiEndpoint: string,
    isMet: boolean,
    metAt: bigint
  ] & {
    conditionType: bigint;
    oracle: string;
    parameters: string;
    threshold: bigint;
    apiEndpoint: string;
    isMet: boolean;
    metAt: bigint;
  };

  export type ConditionalEscrowStruct = {
    id: BigNumberish;
    buyer: AddressLike;
    seller: AddressLike;
    amount: BigNumberish;
    description: string;
    conditions: EscrowConditions.ConditionStruct[];
    createdAt: BigNumberish;
    expiryDate: BigNumberish;
    status: BigNumberish;
    subConditionIds: BigNumberish[];
  };

  export type ConditionalEscrowStructOutput = [
    id: bigint,
    buyer: string,
    seller: string,
    amount: bigint,
    description: string,
    conditions: EscrowConditions.ConditionStructOutput[],
    createdAt: bigint,
    expiryDate: bigint,
    status: bigint,
    subConditionIds: bigint[]
  ] & {
    id: bigint;
    buyer: string;
    seller: string;
    amount: bigint;
    description: string;
    conditions: EscrowConditions.ConditionStructOutput[];
    createdAt: bigint;
    expiryDate: bigint;
    status: bigint;
    subConditionIds: bigint[];
  };
}

export interface EscrowConditionsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_CONDITIONS"
      | "MAX_EXPIRY_DAYS"
      | "addApiCondition"
      | "addMultisigCondition"
      | "addPriceCondition"
      | "addTimestampCondition"
      | "approvalCount"
      | "approveMultisig"
      | "areConditionsMet"
      | "checkConditions"
      | "createConditionalEscrow"
      | "defaultPriceOracle"
      | "escrowCount"
      | "escrows"
      | "getBuyerEscrows"
      | "getConditionStatus"
      | "getEscrow"
      | "hasApproved"
      | "isOracleProvider"
      | "oracleProviders"
      | "owner"
      | "refundIfExpired"
      | "registerOracle"
      | "releaseIfConditionsMet"
      | "setDefaultPriceOracle"
      | "submitApiCallback"
      | "submitPriceUpdate"
      | "usedApiCallbacks"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApiCallbackReceived"
      | "ConditionMet"
      | "ConditionalEscrowCreated"
      | "EscrowReleased"
      | "OracleRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_CONDITIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXPIRY_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addApiCondition",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addMultisigCondition",
    values: [BigNumberish, AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addPriceCondition",
    values: [BigNumberish, boolean, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addTimestampCondition",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvalCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveMultisig",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "areConditionsMet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkConditions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createConditionalEscrow",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerEscrows",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConditionStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOracleProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleProviders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundIfExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOracle",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseIfConditionsMet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitApiCallback",
    values: [BigNumberish, BigNumberish, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPriceUpdate",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usedApiCallbacks",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_CONDITIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXPIRY_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addApiCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMultisigCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPriceCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTimestampCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveMultisig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "areConditionsMet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createConditionalEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConditionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOracleProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundIfExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseIfConditionsMet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitApiCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPriceUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedApiCallbacks",
    data: BytesLike
  ): Result;
}

export namespace ApiCallbackReceivedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    callbackId: BytesLike,
    conditionMet: boolean
  ];
  export type OutputTuple = [
    escrowId: bigint,
    callbackId: string,
    conditionMet: boolean
  ];
  export interface OutputObject {
    escrowId: bigint;
    callbackId: string;
    conditionMet: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionMetEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    conditionIndex: BigNumberish,
    conditionType: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    conditionIndex: bigint,
    conditionType: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    conditionIndex: bigint;
    conditionType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionalEscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish,
    conditionTypes: BigNumberish[]
  ];
  export type OutputTuple = [
    escrowId: bigint,
    buyer: string,
    seller: string,
    amount: bigint,
    conditionTypes: bigint[]
  ];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
    seller: string;
    amount: bigint;
    conditionTypes: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    seller: AddressLike,
    amount: BigNumberish,
    releaseReason: string
  ];
  export type OutputTuple = [
    escrowId: bigint,
    seller: string,
    amount: bigint,
    releaseReason: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    seller: string;
    amount: bigint;
    releaseReason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleRegisteredEvent {
  export type InputTuple = [oracle: AddressLike, name: string];
  export type OutputTuple = [oracle: string, name: string];
  export interface OutputObject {
    oracle: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowConditions extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowConditions;
  waitForDeployment(): Promise<this>;

  interface: EscrowConditionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_CONDITIONS: TypedContractMethod<[], [bigint], "view">;

  MAX_EXPIRY_DAYS: TypedContractMethod<[], [bigint], "view">;

  addApiCondition: TypedContractMethod<
    [_escrowId: BigNumberish, _apiEndpoint: string, _callbackId: BytesLike],
    [void],
    "nonpayable"
  >;

  addMultisigCondition: TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _approvers: AddressLike[],
      _requiredApprovals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addPriceCondition: TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _isAbove: boolean,
      _priceThreshold: BigNumberish,
      _assetPair: string
    ],
    [void],
    "nonpayable"
  >;

  addTimestampCondition: TypedContractMethod<
    [_escrowId: BigNumberish, _targetTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  approvalCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  approveMultisig: TypedContractMethod<
    [_escrowId: BigNumberish, _conditionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  areConditionsMet: TypedContractMethod<
    [_escrowId: BigNumberish],
    [boolean],
    "view"
  >;

  checkConditions: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createConditionalEscrow: TypedContractMethod<
    [_seller: AddressLike, _description: string, _expiryDays: BigNumberish],
    [void],
    "payable"
  >;

  defaultPriceOracle: TypedContractMethod<[], [string], "view">;

  escrowCount: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        buyer: string;
        seller: string;
        amount: bigint;
        description: string;
        createdAt: bigint;
        expiryDate: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getBuyerEscrows: TypedContractMethod<
    [_buyer: AddressLike],
    [bigint[]],
    "view"
  >;

  getConditionStatus: TypedContractMethod<
    [_escrowId: BigNumberish],
    [[boolean[], bigint[]] & { metStatus: boolean[]; metTimestamps: bigint[] }],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [_escrowId: BigNumberish],
    [EscrowConditions.ConditionalEscrowStructOutput],
    "view"
  >;

  hasApproved: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isOracleProvider: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  oracleProviders: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        oracleAddress: string;
        name: string;
        isActive: boolean;
        trustedSince: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refundIfExpired: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerOracle: TypedContractMethod<
    [_oracle: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;

  releaseIfConditionsMet: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDefaultPriceOracle: TypedContractMethod<
    [_oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  submitApiCallback: TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _conditionIndex: BigNumberish,
      _callbackId: BytesLike,
      _conditionMet: boolean
    ],
    [void],
    "nonpayable"
  >;

  submitPriceUpdate: TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _conditionIndex: BigNumberish,
      _currentPrice: BigNumberish,
      _timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  usedApiCallbacks: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_CONDITIONS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EXPIRY_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addApiCondition"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _apiEndpoint: string, _callbackId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addMultisigCondition"
  ): TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _approvers: AddressLike[],
      _requiredApprovals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addPriceCondition"
  ): TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _isAbove: boolean,
      _priceThreshold: BigNumberish,
      _assetPair: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addTimestampCondition"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _targetTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvalCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveMultisig"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _conditionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "areConditionsMet"
  ): TypedContractMethod<[_escrowId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkConditions"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createConditionalEscrow"
  ): TypedContractMethod<
    [_seller: AddressLike, _description: string, _expiryDays: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "defaultPriceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        buyer: string;
        seller: string;
        amount: bigint;
        description: string;
        createdAt: bigint;
        expiryDate: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyerEscrows"
  ): TypedContractMethod<[_buyer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getConditionStatus"
  ): TypedContractMethod<
    [_escrowId: BigNumberish],
    [[boolean[], bigint[]] & { metStatus: boolean[]; metTimestamps: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [_escrowId: BigNumberish],
    [EscrowConditions.ConditionalEscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOracleProvider"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleProviders"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        oracleAddress: string;
        name: string;
        isActive: boolean;
        trustedSince: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundIfExpired"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerOracle"
  ): TypedContractMethod<
    [_oracle: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseIfConditionsMet"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultPriceOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitApiCallback"
  ): TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _conditionIndex: BigNumberish,
      _callbackId: BytesLike,
      _conditionMet: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitPriceUpdate"
  ): TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _conditionIndex: BigNumberish,
      _currentPrice: BigNumberish,
      _timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usedApiCallbacks"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "ApiCallbackReceived"
  ): TypedContractEvent<
    ApiCallbackReceivedEvent.InputTuple,
    ApiCallbackReceivedEvent.OutputTuple,
    ApiCallbackReceivedEvent.OutputObject
  >;
  getEvent(
    key: "ConditionMet"
  ): TypedContractEvent<
    ConditionMetEvent.InputTuple,
    ConditionMetEvent.OutputTuple,
    ConditionMetEvent.OutputObject
  >;
  getEvent(
    key: "ConditionalEscrowCreated"
  ): TypedContractEvent<
    ConditionalEscrowCreatedEvent.InputTuple,
    ConditionalEscrowCreatedEvent.OutputTuple,
    ConditionalEscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OracleRegistered"
  ): TypedContractEvent<
    OracleRegisteredEvent.InputTuple,
    OracleRegisteredEvent.OutputTuple,
    OracleRegisteredEvent.OutputObject
  >;

  filters: {
    "ApiCallbackReceived(uint256,bytes32,bool)": TypedContractEvent<
      ApiCallbackReceivedEvent.InputTuple,
      ApiCallbackReceivedEvent.OutputTuple,
      ApiCallbackReceivedEvent.OutputObject
    >;
    ApiCallbackReceived: TypedContractEvent<
      ApiCallbackReceivedEvent.InputTuple,
      ApiCallbackReceivedEvent.OutputTuple,
      ApiCallbackReceivedEvent.OutputObject
    >;

    "ConditionMet(uint256,uint256,uint8)": TypedContractEvent<
      ConditionMetEvent.InputTuple,
      ConditionMetEvent.OutputTuple,
      ConditionMetEvent.OutputObject
    >;
    ConditionMet: TypedContractEvent<
      ConditionMetEvent.InputTuple,
      ConditionMetEvent.OutputTuple,
      ConditionMetEvent.OutputObject
    >;

    "ConditionalEscrowCreated(uint256,address,address,uint256,uint8[])": TypedContractEvent<
      ConditionalEscrowCreatedEvent.InputTuple,
      ConditionalEscrowCreatedEvent.OutputTuple,
      ConditionalEscrowCreatedEvent.OutputObject
    >;
    ConditionalEscrowCreated: TypedContractEvent<
      ConditionalEscrowCreatedEvent.InputTuple,
      ConditionalEscrowCreatedEvent.OutputTuple,
      ConditionalEscrowCreatedEvent.OutputObject
    >;

    "EscrowReleased(uint256,address,uint256,string)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "OracleRegistered(address,string)": TypedContractEvent<
      OracleRegisteredEvent.InputTuple,
      OracleRegisteredEvent.OutputTuple,
      OracleRegisteredEvent.OutputObject
    >;
    OracleRegistered: TypedContractEvent<
      OracleRegisteredEvent.InputTuple,
      OracleRegisteredEvent.OutputTuple,
      OracleRegisteredEvent.OutputObject
    >;
  };
}
