/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EscrowTemplates {
  export type TemplateContentStruct = {
    title: string;
    description: string;
    defaultAmount: BigNumberish;
    defaultDeadlineDays: BigNumberish;
    milestoneDescriptions: BigNumberish[];
    milestoneAmounts: BigNumberish[];
    terms: string;
  };

  export type TemplateContentStructOutput = [
    title: string,
    description: string,
    defaultAmount: bigint,
    defaultDeadlineDays: bigint,
    milestoneDescriptions: bigint[],
    milestoneAmounts: bigint[],
    terms: string
  ] & {
    title: string;
    description: string;
    defaultAmount: bigint;
    defaultDeadlineDays: bigint;
    milestoneDescriptions: bigint[];
    milestoneAmounts: bigint[];
    terms: string;
  };

  export type TemplateStruct = {
    id: BigNumberish;
    creator: AddressLike;
    name: string;
    description: string;
    templateType: BigNumberish;
    ipfsHash: string;
    price: BigNumberish;
    usageCount: BigNumberish;
    isActive: boolean;
    createdAt: BigNumberish;
  };

  export type TemplateStructOutput = [
    id: bigint,
    creator: string,
    name: string,
    description: string,
    templateType: bigint,
    ipfsHash: string,
    price: bigint,
    usageCount: bigint,
    isActive: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    creator: string;
    name: string;
    description: string;
    templateType: bigint;
    ipfsHash: string;
    price: bigint;
    usageCount: bigint;
    isActive: boolean;
    createdAt: bigint;
  };
}

export interface EscrowTemplatesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PLATFORM_FEE_BPS"
      | "addToFavorites"
      | "canUseTemplate"
      | "createTemplate"
      | "creatorEarnings"
      | "creatorTemplates"
      | "deactivateTemplate"
      | "getCreatorTemplates"
      | "getPopularTemplates"
      | "getTemplate"
      | "getTemplateStats"
      | "getTemplatesByType"
      | "getUserFavorites"
      | "isFavorite"
      | "owner"
      | "platformWallet"
      | "purchaseTemplate"
      | "reactivateTemplate"
      | "removeFromFavorites"
      | "setPlatformFee"
      | "setPlatformWallet"
      | "templateContents"
      | "templateCount"
      | "templates"
      | "templatesByType"
      | "updateTemplate"
      | "useTemplate"
      | "userFavorites"
      | "withdrawEarnings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorWithdrawal"
      | "TemplateCreated"
      | "TemplateDeactivated"
      | "TemplatePurchased"
      | "TemplateUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addToFavorites",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canUseTemplate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTemplate",
    values: [
      string,
      string,
      BigNumberish,
      string,
      BigNumberish,
      EscrowTemplates.TemplateContentStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorTemplates",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateTemplate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorTemplates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPopularTemplates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTemplate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTemplateStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTemplatesByType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserFavorites",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFavorite",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTemplate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateTemplate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromFavorites",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "templateContents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "templateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "templates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "templatesByType",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTemplate",
    values: [BigNumberish, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "useTemplate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userFavorites",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEarnings",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToFavorites",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canUseTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorTemplates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorTemplates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPopularTemplates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTemplateStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTemplatesByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserFavorites",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFavorite", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromFavorites",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "templateContents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "templateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "templates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "templatesByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userFavorites",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEarnings",
    data: BytesLike
  ): Result;
}

export namespace CreatorWithdrawalEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TemplateCreatedEvent {
  export type InputTuple = [
    templateId: BigNumberish,
    creator: AddressLike,
    name: string,
    templateType: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    templateId: bigint,
    creator: string,
    name: string,
    templateType: bigint,
    price: bigint
  ];
  export interface OutputObject {
    templateId: bigint;
    creator: string;
    name: string;
    templateType: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TemplateDeactivatedEvent {
  export type InputTuple = [templateId: BigNumberish];
  export type OutputTuple = [templateId: bigint];
  export interface OutputObject {
    templateId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TemplatePurchasedEvent {
  export type InputTuple = [
    templateId: BigNumberish,
    buyer: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [templateId: bigint, buyer: string, price: bigint];
  export interface OutputObject {
    templateId: bigint;
    buyer: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TemplateUsedEvent {
  export type InputTuple = [
    templateId: BigNumberish,
    user: AddressLike,
    escrowId: BigNumberish
  ];
  export type OutputTuple = [
    templateId: bigint,
    user: string,
    escrowId: bigint
  ];
  export interface OutputObject {
    templateId: bigint;
    user: string;
    escrowId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowTemplates extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowTemplates;
  waitForDeployment(): Promise<this>;

  interface: EscrowTemplatesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  addToFavorites: TypedContractMethod<
    [_templateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  canUseTemplate: TypedContractMethod<
    [_user: AddressLike, _templateId: BigNumberish],
    [boolean],
    "view"
  >;

  createTemplate: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _templateType: BigNumberish,
      _ipfsHash: string,
      _price: BigNumberish,
      _content: EscrowTemplates.TemplateContentStruct
    ],
    [void],
    "nonpayable"
  >;

  creatorEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  creatorTemplates: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  deactivateTemplate: TypedContractMethod<
    [_templateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCreatorTemplates: TypedContractMethod<
    [_creator: AddressLike],
    [bigint[]],
    "view"
  >;

  getPopularTemplates: TypedContractMethod<
    [_count: BigNumberish],
    [EscrowTemplates.TemplateStructOutput[]],
    "view"
  >;

  getTemplate: TypedContractMethod<
    [_templateId: BigNumberish],
    [
      [
        EscrowTemplates.TemplateStructOutput,
        EscrowTemplates.TemplateContentStructOutput
      ]
    ],
    "view"
  >;

  getTemplateStats: TypedContractMethod<
    [_templateId: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        usageCount: bigint;
        earnings: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getTemplatesByType: TypedContractMethod<
    [_type: BigNumberish],
    [EscrowTemplates.TemplateStructOutput[]],
    "view"
  >;

  getUserFavorites: TypedContractMethod<
    [_user: AddressLike],
    [EscrowTemplates.TemplateStructOutput[]],
    "view"
  >;

  isFavorite: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  purchaseTemplate: TypedContractMethod<
    [_templateId: BigNumberish],
    [void],
    "payable"
  >;

  reactivateTemplate: TypedContractMethod<
    [_templateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeFromFavorites: TypedContractMethod<
    [_templateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformWallet: TypedContractMethod<
    [_newWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  templateContents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        title: string;
        description: string;
        defaultAmount: bigint;
        defaultDeadlineDays: bigint;
        terms: string;
      }
    ],
    "view"
  >;

  templateCount: TypedContractMethod<[], [bigint], "view">;

  templates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        templateType: bigint;
        ipfsHash: string;
        price: bigint;
        usageCount: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  templatesByType: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  updateTemplate: TypedContractMethod<
    [
      _templateId: BigNumberish,
      _name: string,
      _description: string,
      _price: BigNumberish,
      _ipfsHash: string
    ],
    [void],
    "nonpayable"
  >;

  useTemplate: TypedContractMethod<
    [_templateId: BigNumberish, _escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userFavorites: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawEarnings: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addToFavorites"
  ): TypedContractMethod<[_templateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canUseTemplate"
  ): TypedContractMethod<
    [_user: AddressLike, _templateId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "createTemplate"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _templateType: BigNumberish,
      _ipfsHash: string,
      _price: BigNumberish,
      _content: EscrowTemplates.TemplateContentStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "creatorTemplates"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateTemplate"
  ): TypedContractMethod<[_templateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCreatorTemplates"
  ): TypedContractMethod<[_creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPopularTemplates"
  ): TypedContractMethod<
    [_count: BigNumberish],
    [EscrowTemplates.TemplateStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTemplate"
  ): TypedContractMethod<
    [_templateId: BigNumberish],
    [
      [
        EscrowTemplates.TemplateStructOutput,
        EscrowTemplates.TemplateContentStructOutput
      ]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTemplateStats"
  ): TypedContractMethod<
    [_templateId: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        usageCount: bigint;
        earnings: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTemplatesByType"
  ): TypedContractMethod<
    [_type: BigNumberish],
    [EscrowTemplates.TemplateStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserFavorites"
  ): TypedContractMethod<
    [_user: AddressLike],
    [EscrowTemplates.TemplateStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFavorite"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseTemplate"
  ): TypedContractMethod<[_templateId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "reactivateTemplate"
  ): TypedContractMethod<[_templateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeFromFavorites"
  ): TypedContractMethod<[_templateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformWallet"
  ): TypedContractMethod<[_newWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "templateContents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        title: string;
        description: string;
        defaultAmount: bigint;
        defaultDeadlineDays: bigint;
        terms: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "templateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "templates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        name: string;
        description: string;
        templateType: bigint;
        ipfsHash: string;
        price: bigint;
        usageCount: bigint;
        isActive: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "templatesByType"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateTemplate"
  ): TypedContractMethod<
    [
      _templateId: BigNumberish,
      _name: string,
      _description: string,
      _price: BigNumberish,
      _ipfsHash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "useTemplate"
  ): TypedContractMethod<
    [_templateId: BigNumberish, _escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userFavorites"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawEarnings"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CreatorWithdrawal"
  ): TypedContractEvent<
    CreatorWithdrawalEvent.InputTuple,
    CreatorWithdrawalEvent.OutputTuple,
    CreatorWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "TemplateCreated"
  ): TypedContractEvent<
    TemplateCreatedEvent.InputTuple,
    TemplateCreatedEvent.OutputTuple,
    TemplateCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TemplateDeactivated"
  ): TypedContractEvent<
    TemplateDeactivatedEvent.InputTuple,
    TemplateDeactivatedEvent.OutputTuple,
    TemplateDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "TemplatePurchased"
  ): TypedContractEvent<
    TemplatePurchasedEvent.InputTuple,
    TemplatePurchasedEvent.OutputTuple,
    TemplatePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "TemplateUsed"
  ): TypedContractEvent<
    TemplateUsedEvent.InputTuple,
    TemplateUsedEvent.OutputTuple,
    TemplateUsedEvent.OutputObject
  >;

  filters: {
    "CreatorWithdrawal(address,uint256)": TypedContractEvent<
      CreatorWithdrawalEvent.InputTuple,
      CreatorWithdrawalEvent.OutputTuple,
      CreatorWithdrawalEvent.OutputObject
    >;
    CreatorWithdrawal: TypedContractEvent<
      CreatorWithdrawalEvent.InputTuple,
      CreatorWithdrawalEvent.OutputTuple,
      CreatorWithdrawalEvent.OutputObject
    >;

    "TemplateCreated(uint256,address,string,uint8,uint256)": TypedContractEvent<
      TemplateCreatedEvent.InputTuple,
      TemplateCreatedEvent.OutputTuple,
      TemplateCreatedEvent.OutputObject
    >;
    TemplateCreated: TypedContractEvent<
      TemplateCreatedEvent.InputTuple,
      TemplateCreatedEvent.OutputTuple,
      TemplateCreatedEvent.OutputObject
    >;

    "TemplateDeactivated(uint256)": TypedContractEvent<
      TemplateDeactivatedEvent.InputTuple,
      TemplateDeactivatedEvent.OutputTuple,
      TemplateDeactivatedEvent.OutputObject
    >;
    TemplateDeactivated: TypedContractEvent<
      TemplateDeactivatedEvent.InputTuple,
      TemplateDeactivatedEvent.OutputTuple,
      TemplateDeactivatedEvent.OutputObject
    >;

    "TemplatePurchased(uint256,address,uint256)": TypedContractEvent<
      TemplatePurchasedEvent.InputTuple,
      TemplatePurchasedEvent.OutputTuple,
      TemplatePurchasedEvent.OutputObject
    >;
    TemplatePurchased: TypedContractEvent<
      TemplatePurchasedEvent.InputTuple,
      TemplatePurchasedEvent.OutputTuple,
      TemplatePurchasedEvent.OutputObject
    >;

    "TemplateUsed(uint256,address,uint256)": TypedContractEvent<
      TemplateUsedEvent.InputTuple,
      TemplateUsedEvent.OutputTuple,
      TemplateUsedEvent.OutputObject
    >;
    TemplateUsed: TypedContractEvent<
      TemplateUsedEvent.InputTuple,
      TemplateUsedEvent.OutputTuple,
      TemplateUsedEvent.OutputObject
    >;
  };
}
