/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EscrowPool {
  export type PoolEscrowStruct = {
    id: BigNumberish;
    seller: AddressLike;
    targetAmount: BigNumberish;
    currentAmount: BigNumberish;
    fundingDeadline: BigNumberish;
    description: string;
    status: BigNumberish;
    releaseVotesWeight: BigNumberish;
    refundVotesWeight: BigNumberish;
    voterCount: BigNumberish;
    creator: AddressLike;
    createdAt: BigNumberish;
  };

  export type PoolEscrowStructOutput = [
    id: bigint,
    seller: string,
    targetAmount: bigint,
    currentAmount: bigint,
    fundingDeadline: bigint,
    description: string,
    status: bigint,
    releaseVotesWeight: bigint,
    refundVotesWeight: bigint,
    voterCount: bigint,
    creator: string,
    createdAt: bigint
  ] & {
    id: bigint;
    seller: string;
    targetAmount: bigint;
    currentAmount: bigint;
    fundingDeadline: bigint;
    description: string;
    status: bigint;
    releaseVotesWeight: bigint;
    refundVotesWeight: bigint;
    voterCount: bigint;
    creator: string;
    createdAt: bigint;
  };
}

export interface EscrowPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_CONTRIBUTION"
      | "REFUND_THRESHOLD_BPS"
      | "RELEASE_THRESHOLD_BPS"
      | "changeVoteToRelease"
      | "claimRefund"
      | "contribute"
      | "contributions"
      | "contributorPools"
      | "createPoolEscrow"
      | "getContribution"
      | "getContributorPools"
      | "getPool"
      | "getPoolsByStatus"
      | "getPoolsPaginated"
      | "getSellerPools"
      | "getVotePercentages"
      | "hasVotedRefund"
      | "hasVotedRelease"
      | "isExpired"
      | "poolCount"
      | "pools"
      | "sellerPools"
      | "voteRefund"
      | "voteRelease"
      | "withdrawContribution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContributionMade"
      | "ContributionWithdrawn"
      | "PoolEscrowCreated"
      | "PoolFunded"
      | "PoolRefunded"
      | "PoolReleased"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_CONTRIBUTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFUND_THRESHOLD_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RELEASE_THRESHOLD_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeVoteToRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contributorPools",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPoolEscrow",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getContribution",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContributorPools",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolsByStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolsPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellerPools",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotePercentages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVotedRefund",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVotedRelease",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "poolCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "pools", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "sellerPools",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawContribution",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_CONTRIBUTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFUND_THRESHOLD_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RELEASE_THRESHOLD_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeVoteToRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributorPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPoolEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContributorPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolsByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolsPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellerPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotePercentages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasVotedRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasVotedRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellerPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteRefund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawContribution",
    data: BytesLike
  ): Result;
}

export namespace ContributionMadeEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish,
    newTotal: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    contributor: string,
    amount: bigint,
    newTotal: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    contributor: string;
    amount: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionWithdrawnEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolEscrowCreatedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    seller: AddressLike,
    creator: AddressLike,
    targetAmount: BigNumberish,
    fundingDeadline: BigNumberish,
    description: string
  ];
  export type OutputTuple = [
    poolId: bigint,
    seller: string,
    creator: string,
    targetAmount: bigint,
    fundingDeadline: bigint,
    description: string
  ];
  export interface OutputObject {
    poolId: bigint;
    seller: string;
    creator: string;
    targetAmount: bigint;
    fundingDeadline: bigint;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFundedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    totalAmount: BigNumberish,
    fundedAt: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    totalAmount: bigint,
    fundedAt: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    totalAmount: bigint;
    fundedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolRefundedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    totalRefunded: BigNumberish,
    refundedAt: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    totalRefunded: bigint,
    refundedAt: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    totalRefunded: bigint;
    refundedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolReleasedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    totalAmount: BigNumberish,
    releasedAt: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    totalAmount: bigint,
    releasedAt: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    totalAmount: bigint;
    releasedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    voter: AddressLike,
    isReleaseVote: boolean,
    weight: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    voter: string,
    isReleaseVote: boolean,
    weight: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    voter: string;
    isReleaseVote: boolean;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowPool extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowPool;
  waitForDeployment(): Promise<this>;

  interface: EscrowPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_CONTRIBUTION: TypedContractMethod<[], [bigint], "view">;

  REFUND_THRESHOLD_BPS: TypedContractMethod<[], [bigint], "view">;

  RELEASE_THRESHOLD_BPS: TypedContractMethod<[], [bigint], "view">;

  changeVoteToRelease: TypedContractMethod<
    [_poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [_poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  contribute: TypedContractMethod<[_poolId: BigNumberish], [void], "payable">;

  contributions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  contributorPools: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  createPoolEscrow: TypedContractMethod<
    [
      _seller: AddressLike,
      _targetAmount: BigNumberish,
      _fundingDeadlineDays: BigNumberish,
      _description: string
    ],
    [void],
    "nonpayable"
  >;

  getContribution: TypedContractMethod<
    [_poolId: BigNumberish, _contributor: AddressLike],
    [bigint],
    "view"
  >;

  getContributorPools: TypedContractMethod<
    [_contributor: AddressLike],
    [bigint[]],
    "view"
  >;

  getPool: TypedContractMethod<
    [_poolId: BigNumberish],
    [EscrowPool.PoolEscrowStructOutput],
    "view"
  >;

  getPoolsByStatus: TypedContractMethod<
    [_status: BigNumberish],
    [bigint[]],
    "view"
  >;

  getPoolsPaginated: TypedContractMethod<
    [_start: BigNumberish, _count: BigNumberish],
    [EscrowPool.PoolEscrowStructOutput[]],
    "view"
  >;

  getSellerPools: TypedContractMethod<
    [_seller: AddressLike],
    [bigint[]],
    "view"
  >;

  getVotePercentages: TypedContractMethod<
    [_poolId: BigNumberish],
    [
      [bigint, bigint] & { releasePercentBps: bigint; refundPercentBps: bigint }
    ],
    "view"
  >;

  hasVotedRefund: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasVotedRelease: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isExpired: TypedContractMethod<[_poolId: BigNumberish], [boolean], "view">;

  poolCount: TypedContractMethod<[], [bigint], "view">;

  pools: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        seller: string;
        targetAmount: bigint;
        currentAmount: bigint;
        fundingDeadline: bigint;
        description: string;
        status: bigint;
        releaseVotesWeight: bigint;
        refundVotesWeight: bigint;
        voterCount: bigint;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  sellerPools: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  voteRefund: TypedContractMethod<
    [_poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  voteRelease: TypedContractMethod<
    [_poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawContribution: TypedContractMethod<
    [_poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_CONTRIBUTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFUND_THRESHOLD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RELEASE_THRESHOLD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "changeVoteToRelease"
  ): TypedContractMethod<[_poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[_poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[_poolId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "contributorPools"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createPoolEscrow"
  ): TypedContractMethod<
    [
      _seller: AddressLike,
      _targetAmount: BigNumberish,
      _fundingDeadlineDays: BigNumberish,
      _description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getContribution"
  ): TypedContractMethod<
    [_poolId: BigNumberish, _contributor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContributorPools"
  ): TypedContractMethod<[_contributor: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<
    [_poolId: BigNumberish],
    [EscrowPool.PoolEscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolsByStatus"
  ): TypedContractMethod<[_status: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPoolsPaginated"
  ): TypedContractMethod<
    [_start: BigNumberish, _count: BigNumberish],
    [EscrowPool.PoolEscrowStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellerPools"
  ): TypedContractMethod<[_seller: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVotePercentages"
  ): TypedContractMethod<
    [_poolId: BigNumberish],
    [
      [bigint, bigint] & { releasePercentBps: bigint; refundPercentBps: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVotedRefund"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVotedRelease"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isExpired"
  ): TypedContractMethod<[_poolId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "poolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        seller: string;
        targetAmount: bigint;
        currentAmount: bigint;
        fundingDeadline: bigint;
        description: string;
        status: bigint;
        releaseVotesWeight: bigint;
        refundVotesWeight: bigint;
        voterCount: bigint;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sellerPools"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "voteRefund"
  ): TypedContractMethod<[_poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteRelease"
  ): TypedContractMethod<[_poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawContribution"
  ): TypedContractMethod<[_poolId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ContributionMade"
  ): TypedContractEvent<
    ContributionMadeEvent.InputTuple,
    ContributionMadeEvent.OutputTuple,
    ContributionMadeEvent.OutputObject
  >;
  getEvent(
    key: "ContributionWithdrawn"
  ): TypedContractEvent<
    ContributionWithdrawnEvent.InputTuple,
    ContributionWithdrawnEvent.OutputTuple,
    ContributionWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "PoolEscrowCreated"
  ): TypedContractEvent<
    PoolEscrowCreatedEvent.InputTuple,
    PoolEscrowCreatedEvent.OutputTuple,
    PoolEscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolFunded"
  ): TypedContractEvent<
    PoolFundedEvent.InputTuple,
    PoolFundedEvent.OutputTuple,
    PoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "PoolRefunded"
  ): TypedContractEvent<
    PoolRefundedEvent.InputTuple,
    PoolRefundedEvent.OutputTuple,
    PoolRefundedEvent.OutputObject
  >;
  getEvent(
    key: "PoolReleased"
  ): TypedContractEvent<
    PoolReleasedEvent.InputTuple,
    PoolReleasedEvent.OutputTuple,
    PoolReleasedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "ContributionMade(uint256,address,uint256,uint256)": TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;
    ContributionMade: TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;

    "ContributionWithdrawn(uint256,address,uint256)": TypedContractEvent<
      ContributionWithdrawnEvent.InputTuple,
      ContributionWithdrawnEvent.OutputTuple,
      ContributionWithdrawnEvent.OutputObject
    >;
    ContributionWithdrawn: TypedContractEvent<
      ContributionWithdrawnEvent.InputTuple,
      ContributionWithdrawnEvent.OutputTuple,
      ContributionWithdrawnEvent.OutputObject
    >;

    "PoolEscrowCreated(uint256,address,address,uint256,uint256,string)": TypedContractEvent<
      PoolEscrowCreatedEvent.InputTuple,
      PoolEscrowCreatedEvent.OutputTuple,
      PoolEscrowCreatedEvent.OutputObject
    >;
    PoolEscrowCreated: TypedContractEvent<
      PoolEscrowCreatedEvent.InputTuple,
      PoolEscrowCreatedEvent.OutputTuple,
      PoolEscrowCreatedEvent.OutputObject
    >;

    "PoolFunded(uint256,uint256,uint256)": TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;
    PoolFunded: TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;

    "PoolRefunded(uint256,uint256,uint256)": TypedContractEvent<
      PoolRefundedEvent.InputTuple,
      PoolRefundedEvent.OutputTuple,
      PoolRefundedEvent.OutputObject
    >;
    PoolRefunded: TypedContractEvent<
      PoolRefundedEvent.InputTuple,
      PoolRefundedEvent.OutputTuple,
      PoolRefundedEvent.OutputObject
    >;

    "PoolReleased(uint256,uint256,uint256)": TypedContractEvent<
      PoolReleasedEvent.InputTuple,
      PoolReleasedEvent.OutputTuple,
      PoolReleasedEvent.OutputObject
    >;
    PoolReleased: TypedContractEvent<
      PoolReleasedEvent.InputTuple,
      PoolReleasedEvent.OutputTuple,
      PoolReleasedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
