/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EscrowInsurance {
  export type ClaimStruct = {
    id: BigNumberish;
    policyId: BigNumberish;
    reason: string;
    evidenceHash: string;
    amountRequested: BigNumberish;
    status: BigNumberish;
    votesFor: BigNumberish;
    votesAgainst: BigNumberish;
    createdAt: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type ClaimStructOutput = [
    id: bigint,
    policyId: bigint,
    reason: string,
    evidenceHash: string,
    amountRequested: bigint,
    status: bigint,
    votesFor: bigint,
    votesAgainst: bigint,
    createdAt: bigint,
    resolvedAt: bigint
  ] & {
    id: bigint;
    policyId: bigint;
    reason: string;
    evidenceHash: string;
    amountRequested: bigint;
    status: bigint;
    votesFor: bigint;
    votesAgainst: bigint;
    createdAt: bigint;
    resolvedAt: bigint;
  };

  export type PolicyStruct = {
    id: BigNumberish;
    buyer: AddressLike;
    escrowId: BigNumberish;
    escrowContract: AddressLike;
    coverageAmount: BigNumberish;
    premiumPaid: BigNumberish;
    expiryDate: BigNumberish;
    claimed: boolean;
    isActive: boolean;
  };

  export type PolicyStructOutput = [
    id: bigint,
    buyer: string,
    escrowId: bigint,
    escrowContract: string,
    coverageAmount: bigint,
    premiumPaid: bigint,
    expiryDate: bigint,
    claimed: boolean,
    isActive: boolean
  ] & {
    id: bigint;
    buyer: string;
    escrowId: bigint;
    escrowContract: string;
    coverageAmount: bigint;
    premiumPaid: bigint;
    expiryDate: bigint;
    claimed: boolean;
    isActive: boolean;
  };
}

export interface EscrowInsuranceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CLAIM_WINDOW_DAYS"
      | "MAX_COVERAGE_BPS"
      | "MIN_STAKE"
      | "MIN_VERIFIER_VOTES"
      | "PREMIUM_RATE_BPS"
      | "REWARD_RATE_BPS"
      | "addVerifier"
      | "claimCount"
      | "claimRewards"
      | "claims"
      | "emergencyWithdraw"
      | "fileClaim"
      | "getClaim"
      | "getPendingClaims"
      | "getPolicy"
      | "getPoolStats"
      | "getStakerInfo"
      | "hasPolicyForEscrow"
      | "hasVoted"
      | "isVerifier"
      | "owner"
      | "policies"
      | "policyCount"
      | "purchasePolicy"
      | "removeVerifier"
      | "stake"
      | "stakers"
      | "totalPoolBalance"
      | "totalStaked"
      | "unstake"
      | "verifiers"
      | "voteOnClaim"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimFiled"
      | "ClaimResolved"
      | "ClaimVoted"
      | "PolicyCreated"
      | "RewardsClaimed"
      | "Staked"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CLAIM_WINDOW_DAYS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_COVERAGE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_VERIFIER_VOTES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PREMIUM_RATE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_RATE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claims",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fileClaim",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingClaims",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakerInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPolicyForEscrow",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "policyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchasePolicy",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "stake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stakers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPoolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnClaim",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "CLAIM_WINDOW_DAYS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_COVERAGE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VERIFIER_VOTES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PREMIUM_RATE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_RATE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fileClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakerInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPolicyForEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchasePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifiers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteOnClaim",
    data: BytesLike
  ): Result;
}

export namespace ClaimFiledEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    policyId: BigNumberish,
    buyer: AddressLike,
    amountRequested: BigNumberish
  ];
  export type OutputTuple = [
    claimId: bigint,
    policyId: bigint,
    buyer: string,
    amountRequested: bigint
  ];
  export interface OutputObject {
    claimId: bigint;
    policyId: bigint;
    buyer: string;
    amountRequested: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimResolvedEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    status: BigNumberish,
    payoutAmount: BigNumberish
  ];
  export type OutputTuple = [
    claimId: bigint,
    status: bigint,
    payoutAmount: bigint
  ];
  export interface OutputObject {
    claimId: bigint;
    status: bigint;
    payoutAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimVotedEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    verifier: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    claimId: bigint,
    verifier: string,
    approved: boolean
  ];
  export interface OutputObject {
    claimId: bigint;
    verifier: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyCreatedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    buyer: AddressLike,
    escrowId: BigNumberish,
    coverageAmount: BigNumberish,
    premium: BigNumberish
  ];
  export type OutputTuple = [
    policyId: bigint,
    buyer: string,
    escrowId: bigint,
    coverageAmount: bigint,
    premium: bigint
  ];
  export interface OutputObject {
    policyId: bigint;
    buyer: string;
    escrowId: bigint;
    coverageAmount: bigint;
    premium: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [staker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [staker: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    staker: AddressLike,
    amount: BigNumberish,
    totalStaked: BigNumberish
  ];
  export type OutputTuple = [
    staker: string,
    amount: bigint,
    totalStaked: bigint
  ];
  export interface OutputObject {
    staker: string;
    amount: bigint;
    totalStaked: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    staker: AddressLike,
    amount: BigNumberish,
    rewards: BigNumberish
  ];
  export type OutputTuple = [staker: string, amount: bigint, rewards: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
    rewards: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowInsurance extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowInsurance;
  waitForDeployment(): Promise<this>;

  interface: EscrowInsuranceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CLAIM_WINDOW_DAYS: TypedContractMethod<[], [bigint], "view">;

  MAX_COVERAGE_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  MIN_VERIFIER_VOTES: TypedContractMethod<[], [bigint], "view">;

  PREMIUM_RATE_BPS: TypedContractMethod<[], [bigint], "view">;

  REWARD_RATE_BPS: TypedContractMethod<[], [bigint], "view">;

  addVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  claimCount: TypedContractMethod<[], [bigint], "view">;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  claims: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        policyId: bigint;
        reason: string;
        evidenceHash: string;
        amountRequested: bigint;
        status: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        createdAt: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fileClaim: TypedContractMethod<
    [
      _policyId: BigNumberish,
      _reason: string,
      _evidenceHash: string,
      _amountRequested: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getClaim: TypedContractMethod<
    [_claimId: BigNumberish],
    [EscrowInsurance.ClaimStructOutput],
    "view"
  >;

  getPendingClaims: TypedContractMethod<[], [bigint[]], "view">;

  getPolicy: TypedContractMethod<
    [_policyId: BigNumberish],
    [EscrowInsurance.PolicyStructOutput],
    "view"
  >;

  getPoolStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalStakedAmount: bigint;
        poolBalance: bigint;
        policyCountTotal: bigint;
        claimCountTotal: bigint;
        verifierCount: bigint;
      }
    ],
    "view"
  >;

  getStakerInfo: TypedContractMethod<
    [_staker: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        accumulatedRewards: bigint;
        pendingRewards: bigint;
        total: bigint;
      }
    ],
    "view"
  >;

  hasPolicyForEscrow: TypedContractMethod<
    [_buyer: AddressLike, _escrowId: BigNumberish],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isVerifier: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: bigint;
        buyer: string;
        escrowId: bigint;
        escrowContract: string;
        coverageAmount: bigint;
        premiumPaid: bigint;
        expiryDate: bigint;
        claimed: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  policyCount: TypedContractMethod<[], [bigint], "view">;

  purchasePolicy: TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _escrowContract: AddressLike,
      _escrowAmount: BigNumberish
    ],
    [void],
    "payable"
  >;

  removeVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[], [void], "payable">;

  stakers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        stakedAt: bigint;
        lastRewardCalc: bigint;
        accumulatedRewards: bigint;
      }
    ],
    "view"
  >;

  totalPoolBalance: TypedContractMethod<[], [bigint], "view">;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  unstake: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  verifiers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  voteOnClaim: TypedContractMethod<
    [_claimId: BigNumberish, _approve: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CLAIM_WINDOW_DAYS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_COVERAGE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VERIFIER_VOTES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PREMIUM_RATE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_RATE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claims"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        policyId: bigint;
        reason: string;
        evidenceHash: string;
        amountRequested: bigint;
        status: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        createdAt: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fileClaim"
  ): TypedContractMethod<
    [
      _policyId: BigNumberish,
      _reason: string,
      _evidenceHash: string,
      _amountRequested: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClaim"
  ): TypedContractMethod<
    [_claimId: BigNumberish],
    [EscrowInsurance.ClaimStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingClaims"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPolicy"
  ): TypedContractMethod<
    [_policyId: BigNumberish],
    [EscrowInsurance.PolicyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalStakedAmount: bigint;
        poolBalance: bigint;
        policyCountTotal: bigint;
        claimCountTotal: bigint;
        verifierCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStakerInfo"
  ): TypedContractMethod<
    [_staker: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        accumulatedRewards: bigint;
        pendingRewards: bigint;
        total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPolicyForEscrow"
  ): TypedContractMethod<
    [_buyer: AddressLike, _escrowId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerifier"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: bigint;
        buyer: string;
        escrowId: bigint;
        escrowContract: string;
        coverageAmount: bigint;
        premiumPaid: bigint;
        expiryDate: bigint;
        claimed: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "policyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchasePolicy"
  ): TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _escrowContract: AddressLike,
      _escrowAmount: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "removeVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "stakers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        amount: bigint;
        stakedAt: bigint;
        lastRewardCalc: bigint;
        accumulatedRewards: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalPoolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "voteOnClaim"
  ): TypedContractMethod<
    [_claimId: BigNumberish, _approve: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ClaimFiled"
  ): TypedContractEvent<
    ClaimFiledEvent.InputTuple,
    ClaimFiledEvent.OutputTuple,
    ClaimFiledEvent.OutputObject
  >;
  getEvent(
    key: "ClaimResolved"
  ): TypedContractEvent<
    ClaimResolvedEvent.InputTuple,
    ClaimResolvedEvent.OutputTuple,
    ClaimResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimVoted"
  ): TypedContractEvent<
    ClaimVotedEvent.InputTuple,
    ClaimVotedEvent.OutputTuple,
    ClaimVotedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyCreated"
  ): TypedContractEvent<
    PolicyCreatedEvent.InputTuple,
    PolicyCreatedEvent.OutputTuple,
    PolicyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "ClaimFiled(uint256,uint256,address,uint256)": TypedContractEvent<
      ClaimFiledEvent.InputTuple,
      ClaimFiledEvent.OutputTuple,
      ClaimFiledEvent.OutputObject
    >;
    ClaimFiled: TypedContractEvent<
      ClaimFiledEvent.InputTuple,
      ClaimFiledEvent.OutputTuple,
      ClaimFiledEvent.OutputObject
    >;

    "ClaimResolved(uint256,uint8,uint256)": TypedContractEvent<
      ClaimResolvedEvent.InputTuple,
      ClaimResolvedEvent.OutputTuple,
      ClaimResolvedEvent.OutputObject
    >;
    ClaimResolved: TypedContractEvent<
      ClaimResolvedEvent.InputTuple,
      ClaimResolvedEvent.OutputTuple,
      ClaimResolvedEvent.OutputObject
    >;

    "ClaimVoted(uint256,address,bool)": TypedContractEvent<
      ClaimVotedEvent.InputTuple,
      ClaimVotedEvent.OutputTuple,
      ClaimVotedEvent.OutputObject
    >;
    ClaimVoted: TypedContractEvent<
      ClaimVotedEvent.InputTuple,
      ClaimVotedEvent.OutputTuple,
      ClaimVotedEvent.OutputObject
    >;

    "PolicyCreated(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;
    PolicyCreated: TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;

    "RewardsClaimed(address,uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "Staked(address,uint256,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(address,uint256,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
