/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EscrowCollateral {
  export type LoanStruct = {
    id: BigNumberish;
    borrower: AddressLike;
    lender: AddressLike;
    escrowId: BigNumberish;
    escrowContract: AddressLike;
    loanAmount: BigNumberish;
    interestRateBps: BigNumberish;
    duration: BigNumberish;
    startTime: BigNumberish;
    dueDate: BigNumberish;
    repaidAmount: BigNumberish;
    status: BigNumberish;
    escrowClaimed: boolean;
  };

  export type LoanStructOutput = [
    id: bigint,
    borrower: string,
    lender: string,
    escrowId: bigint,
    escrowContract: string,
    loanAmount: bigint,
    interestRateBps: bigint,
    duration: bigint,
    startTime: bigint,
    dueDate: bigint,
    repaidAmount: bigint,
    status: bigint,
    escrowClaimed: boolean
  ] & {
    id: bigint;
    borrower: string;
    lender: string;
    escrowId: bigint;
    escrowContract: string;
    loanAmount: bigint;
    interestRateBps: bigint;
    duration: bigint;
    startTime: bigint;
    dueDate: bigint;
    repaidAmount: bigint;
    status: bigint;
    escrowClaimed: boolean;
  };

  export type LoanOfferStruct = {
    id: BigNumberish;
    lender: AddressLike;
    maxAmount: BigNumberish;
    minInterestBps: BigNumberish;
    maxDuration: BigNumberish;
    totalFunded: BigNumberish;
    active: boolean;
  };

  export type LoanOfferStructOutput = [
    id: bigint,
    lender: string,
    maxAmount: bigint,
    minInterestBps: bigint,
    maxDuration: bigint,
    totalFunded: bigint,
    active: boolean
  ] & {
    id: bigint;
    lender: string;
    maxAmount: bigint;
    minInterestBps: bigint;
    maxDuration: bigint;
    totalFunded: bigint;
    active: boolean;
  };
}

export interface EscrowCollateralInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LIQUIDATION_THRESHOLD"
      | "MAX_INTEREST_BPS"
      | "MAX_LTV_BPS"
      | "MIN_INTEREST_BPS"
      | "PLATFORM_FEE_BPS"
      | "borrowerLoans"
      | "calculateTotalDue"
      | "canUseAsCollateral"
      | "cancelOffer"
      | "claimEscrow"
      | "createOffer"
      | "escrowHasActiveLoan"
      | "escrowToLoan"
      | "fundOffer"
      | "getActiveOffers"
      | "getBorrowerLoans"
      | "getHealthFactor"
      | "getLenderLoans"
      | "getLoan"
      | "getOffer"
      | "getRemainingBalance"
      | "lenderLoans"
      | "lenderOffers"
      | "loanCount"
      | "loans"
      | "markDefaulted"
      | "offerCount"
      | "offers"
      | "owner"
      | "platformWallet"
      | "repayLoan"
      | "takeLoan"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Liquidation"
      | "LoanDefaulted"
      | "LoanOfferCreated"
      | "LoanRepaid"
      | "LoanTaken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LIQUIDATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_INTEREST_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LTV_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_INTEREST_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowerLoans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTotalDue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canUseAsCollateral",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOffer",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowHasActiveLoan",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowToLoan",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOffers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lenderLoans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lenderOffers",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loanCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "markDefaulted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "offerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "offers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "takeLoan",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "LIQUIDATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_INTEREST_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LTV_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_INTEREST_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTotalDue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canUseAsCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowHasActiveLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowToLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lenderLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lenderOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDefaulted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "offerCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "offers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "takeLoan", data: BytesLike): Result;
}

export namespace LiquidationEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    liquidator: AddressLike,
    escrowAmount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    liquidator: string,
    escrowAmount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    liquidator: string;
    escrowAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [loanId: BigNumberish, escrowClaimed: BigNumberish];
  export type OutputTuple = [loanId: bigint, escrowClaimed: bigint];
  export interface OutputObject {
    loanId: bigint;
    escrowClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanOfferCreatedEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    lender: AddressLike,
    maxAmount: BigNumberish,
    minInterestBps: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    lender: string,
    maxAmount: bigint,
    minInterestBps: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    lender: string;
    maxAmount: bigint;
    minInterestBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    amount: BigNumberish,
    interest: BigNumberish
  ];
  export type OutputTuple = [loanId: bigint, amount: bigint, interest: bigint];
  export interface OutputObject {
    loanId: bigint;
    amount: bigint;
    interest: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanTakenEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    offerId: BigNumberish,
    borrower: AddressLike,
    escrowId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    offerId: bigint,
    borrower: string,
    escrowId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    offerId: bigint;
    borrower: string;
    escrowId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowCollateral extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowCollateral;
  waitForDeployment(): Promise<this>;

  interface: EscrowCollateralInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LIQUIDATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_INTEREST_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_LTV_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_INTEREST_BPS: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  borrowerLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  calculateTotalDue: TypedContractMethod<
    [_loanId: BigNumberish],
    [bigint],
    "view"
  >;

  canUseAsCollateral: TypedContractMethod<
    [
      _escrowContract: AddressLike,
      _escrowId: BigNumberish,
      _escrowAmount: BigNumberish
    ],
    [[boolean, bigint] & { maxLoan: bigint }],
    "view"
  >;

  cancelOffer: TypedContractMethod<
    [_offerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimEscrow: TypedContractMethod<
    [_loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createOffer: TypedContractMethod<
    [
      _maxAmount: BigNumberish,
      _minInterestBps: BigNumberish,
      _maxDuration: BigNumberish
    ],
    [void],
    "payable"
  >;

  escrowHasActiveLoan: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  escrowToLoan: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  fundOffer: TypedContractMethod<[_offerId: BigNumberish], [void], "payable">;

  getActiveOffers: TypedContractMethod<[], [bigint[]], "view">;

  getBorrowerLoans: TypedContractMethod<
    [_borrower: AddressLike],
    [bigint[]],
    "view"
  >;

  getHealthFactor: TypedContractMethod<
    [_loanId: BigNumberish],
    [bigint],
    "view"
  >;

  getLenderLoans: TypedContractMethod<
    [_lender: AddressLike],
    [bigint[]],
    "view"
  >;

  getLoan: TypedContractMethod<
    [_loanId: BigNumberish],
    [EscrowCollateral.LoanStructOutput],
    "view"
  >;

  getOffer: TypedContractMethod<
    [_offerId: BigNumberish],
    [EscrowCollateral.LoanOfferStructOutput],
    "view"
  >;

  getRemainingBalance: TypedContractMethod<
    [_loanId: BigNumberish],
    [bigint],
    "view"
  >;

  lenderLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  lenderOffers: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  loanCount: TypedContractMethod<[], [bigint], "view">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        borrower: string;
        lender: string;
        escrowId: bigint;
        escrowContract: string;
        loanAmount: bigint;
        interestRateBps: bigint;
        duration: bigint;
        startTime: bigint;
        dueDate: bigint;
        repaidAmount: bigint;
        status: bigint;
        escrowClaimed: boolean;
      }
    ],
    "view"
  >;

  markDefaulted: TypedContractMethod<
    [_loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  offerCount: TypedContractMethod<[], [bigint], "view">;

  offers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        lender: string;
        maxAmount: bigint;
        minInterestBps: bigint;
        maxDuration: bigint;
        totalFunded: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  repayLoan: TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;

  takeLoan: TypedContractMethod<
    [
      _offerId: BigNumberish,
      _escrowId: BigNumberish,
      _escrowContract: AddressLike,
      _amount: BigNumberish,
      _interestBps: BigNumberish,
      _duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LIQUIDATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_INTEREST_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LTV_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_INTEREST_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "borrowerLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateTotalDue"
  ): TypedContractMethod<[_loanId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "canUseAsCollateral"
  ): TypedContractMethod<
    [
      _escrowContract: AddressLike,
      _escrowId: BigNumberish,
      _escrowAmount: BigNumberish
    ],
    [[boolean, bigint] & { maxLoan: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelOffer"
  ): TypedContractMethod<[_offerId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimEscrow"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOffer"
  ): TypedContractMethod<
    [
      _maxAmount: BigNumberish,
      _minInterestBps: BigNumberish,
      _maxDuration: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "escrowHasActiveLoan"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrowToLoan"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundOffer"
  ): TypedContractMethod<[_offerId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getActiveOffers"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getBorrowerLoans"
  ): TypedContractMethod<[_borrower: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getHealthFactor"
  ): TypedContractMethod<[_loanId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLenderLoans"
  ): TypedContractMethod<[_lender: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [_loanId: BigNumberish],
    [EscrowCollateral.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOffer"
  ): TypedContractMethod<
    [_offerId: BigNumberish],
    [EscrowCollateral.LoanOfferStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingBalance"
  ): TypedContractMethod<[_loanId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "lenderLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lenderOffers"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "loanCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        borrower: string;
        lender: string;
        escrowId: bigint;
        escrowContract: string;
        loanAmount: bigint;
        interestRateBps: bigint;
        duration: bigint;
        startTime: bigint;
        dueDate: bigint;
        repaidAmount: bigint;
        status: bigint;
        escrowClaimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDefaulted"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "offerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "offers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        lender: string;
        maxAmount: bigint;
        minInterestBps: bigint;
        maxDuration: bigint;
        totalFunded: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "takeLoan"
  ): TypedContractMethod<
    [
      _offerId: BigNumberish,
      _escrowId: BigNumberish,
      _escrowContract: AddressLike,
      _amount: BigNumberish,
      _interestBps: BigNumberish,
      _duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Liquidation"
  ): TypedContractEvent<
    LiquidationEvent.InputTuple,
    LiquidationEvent.OutputTuple,
    LiquidationEvent.OutputObject
  >;
  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanOfferCreated"
  ): TypedContractEvent<
    LoanOfferCreatedEvent.InputTuple,
    LoanOfferCreatedEvent.OutputTuple,
    LoanOfferCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanTaken"
  ): TypedContractEvent<
    LoanTakenEvent.InputTuple,
    LoanTakenEvent.OutputTuple,
    LoanTakenEvent.OutputObject
  >;

  filters: {
    "Liquidation(uint256,address,uint256)": TypedContractEvent<
      LiquidationEvent.InputTuple,
      LiquidationEvent.OutputTuple,
      LiquidationEvent.OutputObject
    >;
    Liquidation: TypedContractEvent<
      LiquidationEvent.InputTuple,
      LiquidationEvent.OutputTuple,
      LiquidationEvent.OutputObject
    >;

    "LoanDefaulted(uint256,uint256)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanOfferCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      LoanOfferCreatedEvent.InputTuple,
      LoanOfferCreatedEvent.OutputTuple,
      LoanOfferCreatedEvent.OutputObject
    >;
    LoanOfferCreated: TypedContractEvent<
      LoanOfferCreatedEvent.InputTuple,
      LoanOfferCreatedEvent.OutputTuple,
      LoanOfferCreatedEvent.OutputObject
    >;

    "LoanRepaid(uint256,uint256,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanTaken(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      LoanTakenEvent.InputTuple,
      LoanTakenEvent.OutputTuple,
      LoanTakenEvent.OutputObject
    >;
    LoanTaken: TypedContractEvent<
      LoanTakenEvent.InputTuple,
      LoanTakenEvent.OutputTuple,
      LoanTakenEvent.OutputObject
    >;
  };
}
