/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EscrowMarketplace {
  export type EscrowStruct = {
    id: BigNumberish;
    buyer: AddressLike;
    seller: AddressLike;
    amount: BigNumberish;
    description: string;
    createdAt: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
  };

  export type EscrowStructOutput = [
    id: bigint,
    buyer: string,
    seller: string,
    amount: bigint,
    description: string,
    createdAt: bigint,
    deadline: bigint,
    status: bigint
  ] & {
    id: bigint;
    buyer: string;
    seller: string;
    amount: bigint;
    description: string;
    createdAt: bigint;
    deadline: bigint;
    status: bigint;
  };
}

export interface EscrowMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimExpiredRefund"
      | "createEscrow"
      | "createEscrowWithDeadline"
      | "escrowCount"
      | "escrows"
      | "getAllEscrows"
      | "getEscrow"
      | "isExpired"
      | "refundBuyer"
      | "releasePayment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowCreated"
      | "ExpiredRefundClaimed"
      | "PaymentRefunded"
      | "PaymentReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimExpiredRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrowWithDeadline",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEscrows",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundBuyer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimExpiredRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrowWithDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundBuyer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish,
    description: string,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    buyer: string,
    seller: string,
    amount: bigint,
    description: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
    seller: string;
    amount: bigint;
    description: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpiredRefundClaimedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish,
    refundedAt: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    buyer: string,
    amount: bigint,
    refundedAt: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
    amount: bigint;
    refundedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRefundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish,
    refundedAt: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    buyer: string,
    amount: bigint,
    refundedAt: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
    amount: bigint;
    refundedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish,
    releasedAt: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    buyer: string,
    seller: string,
    amount: bigint,
    releasedAt: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    buyer: string;
    seller: string;
    amount: bigint;
    releasedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowMarketplace;
  waitForDeployment(): Promise<this>;

  interface: EscrowMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimExpiredRefund: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [_seller: AddressLike, _description: string],
    [void],
    "payable"
  >;

  createEscrowWithDeadline: TypedContractMethod<
    [_seller: AddressLike, _description: string, _deadlineDays: BigNumberish],
    [void],
    "payable"
  >;

  escrowCount: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        buyer: string;
        seller: string;
        amount: bigint;
        description: string;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getAllEscrows: TypedContractMethod<
    [],
    [EscrowMarketplace.EscrowStructOutput[]],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [_escrowId: BigNumberish],
    [EscrowMarketplace.EscrowStructOutput],
    "view"
  >;

  isExpired: TypedContractMethod<[_escrowId: BigNumberish], [boolean], "view">;

  refundBuyer: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releasePayment: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimExpiredRefund"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [_seller: AddressLike, _description: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createEscrowWithDeadline"
  ): TypedContractMethod<
    [_seller: AddressLike, _description: string, _deadlineDays: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "escrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        buyer: string;
        seller: string;
        amount: bigint;
        description: string;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllEscrows"
  ): TypedContractMethod<[], [EscrowMarketplace.EscrowStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [_escrowId: BigNumberish],
    [EscrowMarketplace.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isExpired"
  ): TypedContractMethod<[_escrowId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "refundBuyer"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpiredRefundClaimed"
  ): TypedContractEvent<
    ExpiredRefundClaimedEvent.InputTuple,
    ExpiredRefundClaimedEvent.OutputTuple,
    ExpiredRefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRefunded"
  ): TypedContractEvent<
    PaymentRefundedEvent.InputTuple,
    PaymentRefundedEvent.OutputTuple,
    PaymentRefundedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;

  filters: {
    "EscrowCreated(uint256,address,address,uint256,string,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "ExpiredRefundClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      ExpiredRefundClaimedEvent.InputTuple,
      ExpiredRefundClaimedEvent.OutputTuple,
      ExpiredRefundClaimedEvent.OutputObject
    >;
    ExpiredRefundClaimed: TypedContractEvent<
      ExpiredRefundClaimedEvent.InputTuple,
      ExpiredRefundClaimedEvent.OutputTuple,
      ExpiredRefundClaimedEvent.OutputObject
    >;

    "PaymentRefunded(uint256,address,uint256,uint256)": TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;
    PaymentRefunded: TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,address,uint256,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
  };
}
