/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EscrowAuction {
  export type BidStruct = {
    seller: AddressLike;
    bidAmount: BigNumberish;
    proposalHash: string;
    timestamp: BigNumberish;
  };

  export type BidStructOutput = [
    seller: string,
    bidAmount: bigint,
    proposalHash: string,
    timestamp: bigint
  ] & {
    seller: string;
    bidAmount: bigint;
    proposalHash: string;
    timestamp: bigint;
  };

  export type AuctionListingStruct = {
    id: BigNumberish;
    buyer: AddressLike;
    jobDescription: string;
    requiredSkills: string;
    maxBudgetWei: BigNumberish;
    startPrice: BigNumberish;
    floorPrice: BigNumberish;
    startTime: BigNumberish;
    duration: BigNumberish;
    decrementPerHour: BigNumberish;
    filled: boolean;
    winningBidIndex: BigNumberish;
    winner: AddressLike;
  };

  export type AuctionListingStructOutput = [
    id: bigint,
    buyer: string,
    jobDescription: string,
    requiredSkills: string,
    maxBudgetWei: bigint,
    startPrice: bigint,
    floorPrice: bigint,
    startTime: bigint,
    duration: bigint,
    decrementPerHour: bigint,
    filled: boolean,
    winningBidIndex: bigint,
    winner: string
  ] & {
    id: bigint;
    buyer: string;
    jobDescription: string;
    requiredSkills: string;
    maxBudgetWei: bigint;
    startPrice: bigint;
    floorPrice: bigint;
    startTime: bigint;
    duration: bigint;
    decrementPerHour: bigint;
    filled: boolean;
    winningBidIndex: bigint;
    winner: string;
  };
}

export interface EscrowAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_DURATION"
      | "MIN_BID"
      | "MIN_DURATION"
      | "acceptBid"
      | "bids"
      | "buyerListings"
      | "cancelListing"
      | "createListing"
      | "escrowMarketplace"
      | "getBids"
      | "getBuyerListings"
      | "getCurrentPrice"
      | "getListing"
      | "getPriceCurve"
      | "getSellerBids"
      | "getTimeRemaining"
      | "listingCount"
      | "listings"
      | "placeBid"
      | "sellerBids"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidAccepted"
      | "BidPlaced"
      | "ListingCancelled"
      | "ListingCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_BID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bids",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyerListings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createListing",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowMarketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBids",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerListings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceCurve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellerBids",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeRemaining",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listingCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBid",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sellerBids",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_BID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyerListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceCurve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellerBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellerBids", data: BytesLike): Result;
}

export namespace BidAcceptedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    seller: AddressLike,
    finalPrice: BigNumberish,
    escrowId: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    seller: string,
    finalPrice: bigint,
    escrowId: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
    finalPrice: bigint;
    escrowId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    seller: AddressLike,
    bidAmount: BigNumberish,
    proposalHash: string
  ];
  export type OutputTuple = [
    listingId: bigint,
    seller: string,
    bidAmount: bigint,
    proposalHash: string
  ];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
    bidAmount: bigint;
    proposalHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCancelledEvent {
  export type InputTuple = [listingId: BigNumberish, cancelledAt: BigNumberish];
  export type OutputTuple = [listingId: bigint, cancelledAt: bigint];
  export interface OutputObject {
    listingId: bigint;
    cancelledAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCreatedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    buyer: AddressLike,
    maxBudget: BigNumberish,
    startPrice: BigNumberish,
    floorPrice: BigNumberish,
    startTime: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    buyer: string,
    maxBudget: bigint,
    startPrice: bigint,
    floorPrice: bigint,
    startTime: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    buyer: string;
    maxBudget: bigint;
    startPrice: bigint;
    floorPrice: bigint;
    startTime: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowAuction extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowAuction;
  waitForDeployment(): Promise<this>;

  interface: EscrowAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_BID: TypedContractMethod<[], [bigint], "view">;

  MIN_DURATION: TypedContractMethod<[], [bigint], "view">;

  acceptBid: TypedContractMethod<
    [_listingId: BigNumberish, _bidIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  bids: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint] & {
        seller: string;
        bidAmount: bigint;
        proposalHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  buyerListings: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  cancelListing: TypedContractMethod<
    [_listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createListing: TypedContractMethod<
    [
      _jobDescription: string,
      _skills: string,
      _maxBudget: BigNumberish,
      _floorPrice: BigNumberish,
      _durationHours: BigNumberish,
      _decrementPerHour: BigNumberish
    ],
    [void],
    "payable"
  >;

  escrowMarketplace: TypedContractMethod<[], [string], "view">;

  getBids: TypedContractMethod<
    [_listingId: BigNumberish],
    [EscrowAuction.BidStructOutput[]],
    "view"
  >;

  getBuyerListings: TypedContractMethod<
    [_buyer: AddressLike],
    [bigint[]],
    "view"
  >;

  getCurrentPrice: TypedContractMethod<
    [_listingId: BigNumberish],
    [bigint],
    "view"
  >;

  getListing: TypedContractMethod<
    [_listingId: BigNumberish],
    [EscrowAuction.AuctionListingStructOutput],
    "view"
  >;

  getPriceCurve: TypedContractMethod<
    [_listingId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        startPrice: bigint;
        floorPrice: bigint;
        currentPrice: bigint;
        decrementPerHour: bigint;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;

  getSellerBids: TypedContractMethod<
    [_seller: AddressLike],
    [bigint[]],
    "view"
  >;

  getTimeRemaining: TypedContractMethod<
    [_listingId: BigNumberish],
    [bigint],
    "view"
  >;

  listingCount: TypedContractMethod<[], [bigint], "view">;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        id: bigint;
        buyer: string;
        jobDescription: string;
        requiredSkills: string;
        maxBudgetWei: bigint;
        startPrice: bigint;
        floorPrice: bigint;
        startTime: bigint;
        duration: bigint;
        decrementPerHour: bigint;
        filled: boolean;
        winningBidIndex: bigint;
        winner: string;
      }
    ],
    "view"
  >;

  placeBid: TypedContractMethod<
    [_listingId: BigNumberish, _proposalHash: string],
    [void],
    "nonpayable"
  >;

  sellerBids: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<
    [_listingId: BigNumberish, _bidIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint] & {
        seller: string;
        bidAmount: bigint;
        proposalHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "buyerListings"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[_listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createListing"
  ): TypedContractMethod<
    [
      _jobDescription: string,
      _skills: string,
      _maxBudget: BigNumberish,
      _floorPrice: BigNumberish,
      _durationHours: BigNumberish,
      _decrementPerHour: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "escrowMarketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBids"
  ): TypedContractMethod<
    [_listingId: BigNumberish],
    [EscrowAuction.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyerListings"
  ): TypedContractMethod<[_buyer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[_listingId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [_listingId: BigNumberish],
    [EscrowAuction.AuctionListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceCurve"
  ): TypedContractMethod<
    [_listingId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        startPrice: bigint;
        floorPrice: bigint;
        currentPrice: bigint;
        decrementPerHour: bigint;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellerBids"
  ): TypedContractMethod<[_seller: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTimeRemaining"
  ): TypedContractMethod<[_listingId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "listingCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        id: bigint;
        buyer: string;
        jobDescription: string;
        requiredSkills: string;
        maxBudgetWei: bigint;
        startPrice: bigint;
        floorPrice: bigint;
        startTime: bigint;
        duration: bigint;
        decrementPerHour: bigint;
        filled: boolean;
        winningBidIndex: bigint;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeBid"
  ): TypedContractMethod<
    [_listingId: BigNumberish, _proposalHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellerBids"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "BidAccepted"
  ): TypedContractEvent<
    BidAcceptedEvent.InputTuple,
    BidAcceptedEvent.OutputTuple,
    BidAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "ListingCancelled"
  ): TypedContractEvent<
    ListingCancelledEvent.InputTuple,
    ListingCancelledEvent.OutputTuple,
    ListingCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ListingCreated"
  ): TypedContractEvent<
    ListingCreatedEvent.InputTuple,
    ListingCreatedEvent.OutputTuple,
    ListingCreatedEvent.OutputObject
  >;

  filters: {
    "BidAccepted(uint256,address,uint256,uint256)": TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;
    BidAccepted: TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;

    "BidPlaced(uint256,address,uint256,string)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "ListingCancelled(uint256,uint256)": TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;
    ListingCancelled: TypedContractEvent<
      ListingCancelledEvent.InputTuple,
      ListingCancelledEvent.OutputTuple,
      ListingCancelledEvent.OutputObject
    >;

    "ListingCreated(uint256,address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;
    ListingCreated: TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;
  };
}
