/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "EscrowMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowMarketplace__factory>;
    getContractFactory(
      name: "EscrowAuction",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowAuction__factory>;
    getContractFactory(
      name: "EscrowCollateral",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowCollateral__factory>;
    getContractFactory(
      name: "EscrowConditions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowConditions__factory>;
    getContractFactory(
      name: "EscrowInsurance",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowInsurance__factory>;
    getContractFactory(
      name: "EscrowPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowPool__factory>;
    getContractFactory(
      name: "EscrowTemplates",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EscrowTemplates__factory>;
    getContractFactory(
      name: "SubscriptionEscrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SubscriptionEscrow__factory>;
    getContractFactory(
      name: "TrustGraph",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustGraph__factory>;
    getContractFactory(
      name: "ZKPrivateEscrow",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZKPrivateEscrow__factory>;

    getContractAt(
      name: "EscrowMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowMarketplace>;
    getContractAt(
      name: "EscrowAuction",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowAuction>;
    getContractAt(
      name: "EscrowCollateral",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowCollateral>;
    getContractAt(
      name: "EscrowConditions",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowConditions>;
    getContractAt(
      name: "EscrowInsurance",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowInsurance>;
    getContractAt(
      name: "EscrowPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowPool>;
    getContractAt(
      name: "EscrowTemplates",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EscrowTemplates>;
    getContractAt(
      name: "SubscriptionEscrow",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SubscriptionEscrow>;
    getContractAt(
      name: "TrustGraph",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustGraph>;
    getContractAt(
      name: "ZKPrivateEscrow",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZKPrivateEscrow>;

    deployContract(
      name: "EscrowMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowMarketplace>;
    deployContract(
      name: "EscrowAuction",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowAuction>;
    deployContract(
      name: "EscrowCollateral",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowCollateral>;
    deployContract(
      name: "EscrowConditions",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowConditions>;
    deployContract(
      name: "EscrowInsurance",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowInsurance>;
    deployContract(
      name: "EscrowPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowPool>;
    deployContract(
      name: "EscrowTemplates",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowTemplates>;
    deployContract(
      name: "SubscriptionEscrow",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubscriptionEscrow>;
    deployContract(
      name: "TrustGraph",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustGraph>;
    deployContract(
      name: "ZKPrivateEscrow",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZKPrivateEscrow>;

    deployContract(
      name: "EscrowMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowMarketplace>;
    deployContract(
      name: "EscrowAuction",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowAuction>;
    deployContract(
      name: "EscrowCollateral",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowCollateral>;
    deployContract(
      name: "EscrowConditions",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowConditions>;
    deployContract(
      name: "EscrowInsurance",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowInsurance>;
    deployContract(
      name: "EscrowPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowPool>;
    deployContract(
      name: "EscrowTemplates",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EscrowTemplates>;
    deployContract(
      name: "SubscriptionEscrow",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubscriptionEscrow>;
    deployContract(
      name: "TrustGraph",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustGraph>;
    deployContract(
      name: "ZKPrivateEscrow",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZKPrivateEscrow>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
