/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SubscriptionEscrow {
  export type SubscriptionStruct = {
    id: BigNumberish;
    buyer: AddressLike;
    seller: AddressLike;
    amountPerCycle: BigNumberish;
    totalCycles: BigNumberish;
    cyclesCompleted: BigNumberish;
    nextReleaseAt: BigNumberish;
    intervalSeconds: BigNumberish;
    vaultBalance: BigNumberish;
    status: BigNumberish;
    description: string;
    createdAt: BigNumberish;
  };

  export type SubscriptionStructOutput = [
    id: bigint,
    buyer: string,
    seller: string,
    amountPerCycle: bigint,
    totalCycles: bigint,
    cyclesCompleted: bigint,
    nextReleaseAt: bigint,
    intervalSeconds: bigint,
    vaultBalance: bigint,
    status: bigint,
    description: string,
    createdAt: bigint
  ] & {
    id: bigint;
    buyer: string;
    seller: string;
    amountPerCycle: bigint;
    totalCycles: bigint;
    cyclesCompleted: bigint;
    nextReleaseAt: bigint;
    intervalSeconds: bigint;
    vaultBalance: bigint;
    status: bigint;
    description: string;
    createdAt: bigint;
  };
}

export interface SubscriptionEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_CYCLES"
      | "MAX_INTERVAL"
      | "MIN_CYCLE_AMOUNT"
      | "MIN_INTERVAL"
      | "buyerSubscriptions"
      | "cancelSubscription"
      | "createSubscription"
      | "getActiveSubscriptions"
      | "getBuyerSubscriptions"
      | "getProgressBps"
      | "getReleasableSubscriptions"
      | "getSellerSubscriptions"
      | "getSubscription"
      | "getSubscriptionsPaginated"
      | "getTimeUntilNextRelease"
      | "isReleaseReady"
      | "sellerSubscriptions"
      | "subscriptionCount"
      | "subscriptions"
      | "topUpSubscription"
      | "triggerRelease"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CycleReleased"
      | "SubscriptionCancelled"
      | "SubscriptionCompleted"
      | "SubscriptionCreated"
      | "SubscriptionToppedUp"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_CYCLES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_CYCLE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyerSubscriptions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveSubscriptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerSubscriptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProgressBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReleasableSubscriptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellerSubscriptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptionsPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeUntilNextRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isReleaseReady",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellerSubscriptions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "topUpSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerRelease",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_CYCLES", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_CYCLE_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyerSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProgressBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReleasableSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellerSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptionsPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeUntilNextRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReleaseReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellerSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topUpSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerRelease",
    data: BytesLike
  ): Result;
}

export namespace CycleReleasedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    cycleNumber: BigNumberish,
    amount: BigNumberish,
    releasedAt: BigNumberish,
    triggeredBy: AddressLike
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    cycleNumber: bigint,
    amount: bigint,
    releasedAt: bigint,
    triggeredBy: string
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    cycleNumber: bigint;
    amount: bigint;
    releasedAt: bigint;
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    refundAmount: BigNumberish,
    cancelledAt: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    refundAmount: bigint,
    cancelledAt: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    refundAmount: bigint;
    cancelledAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCompletedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    totalReleased: BigNumberish,
    completedAt: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    totalReleased: bigint,
    completedAt: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    totalReleased: bigint;
    completedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    amountPerCycle: BigNumberish,
    totalCycles: BigNumberish,
    intervalSeconds: BigNumberish,
    nextReleaseAt: BigNumberish,
    description: string
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    buyer: string,
    seller: string,
    amountPerCycle: bigint,
    totalCycles: bigint,
    intervalSeconds: bigint,
    nextReleaseAt: bigint,
    description: string
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    buyer: string;
    seller: string;
    amountPerCycle: bigint;
    totalCycles: bigint;
    intervalSeconds: bigint;
    nextReleaseAt: bigint;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionToppedUpEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    addedCycles: BigNumberish,
    newTotalCycles: BigNumberish,
    newVaultBalance: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    addedCycles: bigint,
    newTotalCycles: bigint,
    newVaultBalance: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    addedCycles: bigint;
    newTotalCycles: bigint;
    newVaultBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubscriptionEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionEscrow;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_CYCLES: TypedContractMethod<[], [bigint], "view">;

  MAX_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  MIN_CYCLE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  MIN_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  buyerSubscriptions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  cancelSubscription: TypedContractMethod<
    [_subId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSubscription: TypedContractMethod<
    [
      _seller: AddressLike,
      _cycles: BigNumberish,
      _intervalSeconds: BigNumberish,
      _description: string
    ],
    [void],
    "payable"
  >;

  getActiveSubscriptions: TypedContractMethod<
    [_buyer: AddressLike],
    [bigint[]],
    "view"
  >;

  getBuyerSubscriptions: TypedContractMethod<
    [_buyer: AddressLike],
    [bigint[]],
    "view"
  >;

  getProgressBps: TypedContractMethod<[_subId: BigNumberish], [bigint], "view">;

  getReleasableSubscriptions: TypedContractMethod<
    [_withinSeconds: BigNumberish],
    [bigint[]],
    "view"
  >;

  getSellerSubscriptions: TypedContractMethod<
    [_seller: AddressLike],
    [bigint[]],
    "view"
  >;

  getSubscription: TypedContractMethod<
    [_subId: BigNumberish],
    [SubscriptionEscrow.SubscriptionStructOutput],
    "view"
  >;

  getSubscriptionsPaginated: TypedContractMethod<
    [_start: BigNumberish, _count: BigNumberish],
    [SubscriptionEscrow.SubscriptionStructOutput[]],
    "view"
  >;

  getTimeUntilNextRelease: TypedContractMethod<
    [_subId: BigNumberish],
    [bigint],
    "view"
  >;

  isReleaseReady: TypedContractMethod<
    [_subId: BigNumberish],
    [boolean],
    "view"
  >;

  sellerSubscriptions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  subscriptionCount: TypedContractMethod<[], [bigint], "view">;

  subscriptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        buyer: string;
        seller: string;
        amountPerCycle: bigint;
        totalCycles: bigint;
        cyclesCompleted: bigint;
        nextReleaseAt: bigint;
        intervalSeconds: bigint;
        vaultBalance: bigint;
        status: bigint;
        description: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  topUpSubscription: TypedContractMethod<
    [_subId: BigNumberish],
    [void],
    "payable"
  >;

  triggerRelease: TypedContractMethod<
    [_subId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_CYCLES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_CYCLE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyerSubscriptions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelSubscription"
  ): TypedContractMethod<[_subId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSubscription"
  ): TypedContractMethod<
    [
      _seller: AddressLike,
      _cycles: BigNumberish,
      _intervalSeconds: BigNumberish,
      _description: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getActiveSubscriptions"
  ): TypedContractMethod<[_buyer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getBuyerSubscriptions"
  ): TypedContractMethod<[_buyer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProgressBps"
  ): TypedContractMethod<[_subId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReleasableSubscriptions"
  ): TypedContractMethod<[_withinSeconds: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSellerSubscriptions"
  ): TypedContractMethod<[_seller: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [_subId: BigNumberish],
    [SubscriptionEscrow.SubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubscriptionsPaginated"
  ): TypedContractMethod<
    [_start: BigNumberish, _count: BigNumberish],
    [SubscriptionEscrow.SubscriptionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTimeUntilNextRelease"
  ): TypedContractMethod<[_subId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isReleaseReady"
  ): TypedContractMethod<[_subId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "sellerSubscriptions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "subscriptionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        buyer: string;
        seller: string;
        amountPerCycle: bigint;
        totalCycles: bigint;
        cyclesCompleted: bigint;
        nextReleaseAt: bigint;
        intervalSeconds: bigint;
        vaultBalance: bigint;
        status: bigint;
        description: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "topUpSubscription"
  ): TypedContractMethod<[_subId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "triggerRelease"
  ): TypedContractMethod<[_subId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CycleReleased"
  ): TypedContractEvent<
    CycleReleasedEvent.InputTuple,
    CycleReleasedEvent.OutputTuple,
    CycleReleasedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCompleted"
  ): TypedContractEvent<
    SubscriptionCompletedEvent.InputTuple,
    SubscriptionCompletedEvent.OutputTuple,
    SubscriptionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionToppedUp"
  ): TypedContractEvent<
    SubscriptionToppedUpEvent.InputTuple,
    SubscriptionToppedUpEvent.OutputTuple,
    SubscriptionToppedUpEvent.OutputObject
  >;

  filters: {
    "CycleReleased(uint256,uint256,uint256,uint256,address)": TypedContractEvent<
      CycleReleasedEvent.InputTuple,
      CycleReleasedEvent.OutputTuple,
      CycleReleasedEvent.OutputObject
    >;
    CycleReleased: TypedContractEvent<
      CycleReleasedEvent.InputTuple,
      CycleReleasedEvent.OutputTuple,
      CycleReleasedEvent.OutputObject
    >;

    "SubscriptionCancelled(uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionCompleted(uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionCompletedEvent.InputTuple,
      SubscriptionCompletedEvent.OutputTuple,
      SubscriptionCompletedEvent.OutputObject
    >;
    SubscriptionCompleted: TypedContractEvent<
      SubscriptionCompletedEvent.InputTuple,
      SubscriptionCompletedEvent.OutputTuple,
      SubscriptionCompletedEvent.OutputObject
    >;

    "SubscriptionCreated(uint256,address,address,uint256,uint256,uint256,uint256,string)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;

    "SubscriptionToppedUp(uint256,uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionToppedUpEvent.InputTuple,
      SubscriptionToppedUpEvent.OutputTuple,
      SubscriptionToppedUpEvent.OutputObject
    >;
    SubscriptionToppedUp: TypedContractEvent<
      SubscriptionToppedUpEvent.InputTuple,
      SubscriptionToppedUpEvent.OutputTuple,
      SubscriptionToppedUpEvent.OutputObject
    >;
  };
}
