/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TrustGraph {
  export type TrustEdgeStruct = {
    from: AddressLike;
    to: AddressLike;
    weight: BigNumberish;
    timestamp: BigNumberish;
    escrowId: BigNumberish;
  };

  export type TrustEdgeStructOutput = [
    from: string,
    to: string,
    weight: bigint,
    timestamp: bigint,
    escrowId: bigint
  ] & {
    from: string;
    to: string;
    weight: bigint;
    timestamp: bigint;
    escrowId: bigint;
  };
}

export interface TrustGraphInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPLETED_WEIGHT"
      | "DISPUTED_WEIGHT"
      | "MAX_SCORE"
      | "MIN_SCORE"
      | "REFUNDED_WEIGHT"
      | "authorizeEscrowContract"
      | "authorizedEscrowContracts"
      | "getConnectionStrength"
      | "getDealStats"
      | "getIncomingEdges"
      | "getOutgoingEdges"
      | "getTopTrusted"
      | "getTrustPath"
      | "getTrustScore"
      | "getTrustTier"
      | "hasMutualConnection"
      | "incomingEdges"
      | "outgoingEdges"
      | "owner"
      | "recordTrustEdge"
      | "revokeEscrowContract"
      | "totalDeals"
      | "trustScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowContractAuthorized"
      | "TrustEdgeRecorded"
      | "TrustScoreUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPLETED_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTED_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_SCORE", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_SCORE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REFUNDED_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeEscrowContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedEscrowContracts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConnectionStrength",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDealStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIncomingEdges",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutgoingEdges",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTopTrusted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustPath",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasMutualConnection",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incomingEdges",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "outgoingEdges",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordTrustEdge",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeEscrowContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustScore",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPLETED_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTED_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SCORE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_SCORE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REFUNDED_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeEscrowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedEscrowContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConnectionStrength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDealStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIncomingEdges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutgoingEdges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopTrusted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustPath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasMutualConnection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incomingEdges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "outgoingEdges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordTrustEdge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeEscrowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalDeals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trustScore", data: BytesLike): Result;
}

export namespace EscrowContractAuthorizedEvent {
  export type InputTuple = [escrowContract: AddressLike];
  export type OutputTuple = [escrowContract: string];
  export interface OutputObject {
    escrowContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustEdgeRecordedEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    weight: BigNumberish,
    escrowId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    weight: bigint,
    escrowId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    weight: bigint;
    escrowId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustScoreUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    newScore: BigNumberish,
    totalDeals: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    newScore: bigint,
    totalDeals: bigint
  ];
  export interface OutputObject {
    user: string;
    newScore: bigint;
    totalDeals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustGraph extends BaseContract {
  connect(runner?: ContractRunner | null): TrustGraph;
  waitForDeployment(): Promise<this>;

  interface: TrustGraphInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPLETED_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  DISPUTED_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  MIN_SCORE: TypedContractMethod<[], [bigint], "view">;

  REFUNDED_WEIGHT: TypedContractMethod<[], [bigint], "view">;

  authorizeEscrowContract: TypedContractMethod<
    [_contract: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedEscrowContracts: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getConnectionStrength: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike],
    [bigint],
    "view"
  >;

  getDealStats: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        completed: bigint;
        refunded: bigint;
        disputed: bigint;
      }
    ],
    "view"
  >;

  getIncomingEdges: TypedContractMethod<
    [_user: AddressLike],
    [TrustGraph.TrustEdgeStructOutput[]],
    "view"
  >;

  getOutgoingEdges: TypedContractMethod<
    [_user: AddressLike],
    [TrustGraph.TrustEdgeStructOutput[]],
    "view"
  >;

  getTopTrusted: TypedContractMethod<
    [_count: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;

  getTrustPath: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike],
    [[boolean, bigint] & { connected: boolean; avgTrust: bigint }],
    "view"
  >;

  getTrustScore: TypedContractMethod<
    [_user: AddressLike],
    [[bigint, bigint] & { score: bigint; deals: bigint }],
    "view"
  >;

  getTrustTier: TypedContractMethod<[_user: AddressLike], [string], "view">;

  hasMutualConnection: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  incomingEdges: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        from: string;
        to: string;
        weight: bigint;
        timestamp: bigint;
        escrowId: bigint;
      }
    ],
    "view"
  >;

  outgoingEdges: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        from: string;
        to: string;
        weight: bigint;
        timestamp: bigint;
        escrowId: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordTrustEdge: TypedContractMethod<
    [
      _from: AddressLike,
      _to: AddressLike,
      _weight: BigNumberish,
      _escrowId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  revokeEscrowContract: TypedContractMethod<
    [_contract: AddressLike],
    [void],
    "nonpayable"
  >;

  totalDeals: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  trustScore: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPLETED_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTED_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFUNDED_WEIGHT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizeEscrowContract"
  ): TypedContractMethod<[_contract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedEscrowContracts"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getConnectionStrength"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDealStats"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        completed: bigint;
        refunded: bigint;
        disputed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIncomingEdges"
  ): TypedContractMethod<
    [_user: AddressLike],
    [TrustGraph.TrustEdgeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOutgoingEdges"
  ): TypedContractMethod<
    [_user: AddressLike],
    [TrustGraph.TrustEdgeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopTrusted"
  ): TypedContractMethod<
    [_count: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTrustPath"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike],
    [[boolean, bigint] & { connected: boolean; avgTrust: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTrustScore"
  ): TypedContractMethod<
    [_user: AddressLike],
    [[bigint, bigint] & { score: bigint; deals: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTrustTier"
  ): TypedContractMethod<[_user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasMutualConnection"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "incomingEdges"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        from: string;
        to: string;
        weight: bigint;
        timestamp: bigint;
        escrowId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "outgoingEdges"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        from: string;
        to: string;
        weight: bigint;
        timestamp: bigint;
        escrowId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordTrustEdge"
  ): TypedContractMethod<
    [
      _from: AddressLike,
      _to: AddressLike,
      _weight: BigNumberish,
      _escrowId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeEscrowContract"
  ): TypedContractMethod<[_contract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalDeals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "trustScore"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "EscrowContractAuthorized"
  ): TypedContractEvent<
    EscrowContractAuthorizedEvent.InputTuple,
    EscrowContractAuthorizedEvent.OutputTuple,
    EscrowContractAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "TrustEdgeRecorded"
  ): TypedContractEvent<
    TrustEdgeRecordedEvent.InputTuple,
    TrustEdgeRecordedEvent.OutputTuple,
    TrustEdgeRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TrustScoreUpdated"
  ): TypedContractEvent<
    TrustScoreUpdatedEvent.InputTuple,
    TrustScoreUpdatedEvent.OutputTuple,
    TrustScoreUpdatedEvent.OutputObject
  >;

  filters: {
    "EscrowContractAuthorized(address)": TypedContractEvent<
      EscrowContractAuthorizedEvent.InputTuple,
      EscrowContractAuthorizedEvent.OutputTuple,
      EscrowContractAuthorizedEvent.OutputObject
    >;
    EscrowContractAuthorized: TypedContractEvent<
      EscrowContractAuthorizedEvent.InputTuple,
      EscrowContractAuthorizedEvent.OutputTuple,
      EscrowContractAuthorizedEvent.OutputObject
    >;

    "TrustEdgeRecorded(address,address,uint8,uint256,uint256)": TypedContractEvent<
      TrustEdgeRecordedEvent.InputTuple,
      TrustEdgeRecordedEvent.OutputTuple,
      TrustEdgeRecordedEvent.OutputObject
    >;
    TrustEdgeRecorded: TypedContractEvent<
      TrustEdgeRecordedEvent.InputTuple,
      TrustEdgeRecordedEvent.OutputTuple,
      TrustEdgeRecordedEvent.OutputObject
    >;

    "TrustScoreUpdated(address,uint256,uint256)": TypedContractEvent<
      TrustScoreUpdatedEvent.InputTuple,
      TrustScoreUpdatedEvent.OutputTuple,
      TrustScoreUpdatedEvent.OutputObject
    >;
    TrustScoreUpdated: TypedContractEvent<
      TrustScoreUpdatedEvent.InputTuple,
      TrustScoreUpdatedEvent.OutputTuple,
      TrustScoreUpdatedEvent.OutputObject
    >;
  };
}
