/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ZKPrivateEscrow {
  export type PrivateEscrowStruct = {
    id: BigNumberish;
    commitmentHash: BytesLike;
    seller: AddressLike;
    amount: BigNumberish;
    privacyLevel: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    revealDeadline: BigNumberish;
    completionDeadline: BigNumberish;
    zkProofHash: BytesLike;
    publicMetadata: string;
    revealer: AddressLike;
    revealedAt: BigNumberish;
  };

  export type PrivateEscrowStructOutput = [
    id: bigint,
    commitmentHash: string,
    seller: string,
    amount: bigint,
    privacyLevel: bigint,
    status: bigint,
    createdAt: bigint,
    revealDeadline: bigint,
    completionDeadline: bigint,
    zkProofHash: string,
    publicMetadata: string,
    revealer: string,
    revealedAt: bigint
  ] & {
    id: bigint;
    commitmentHash: string;
    seller: string;
    amount: bigint;
    privacyLevel: bigint;
    status: bigint;
    createdAt: bigint;
    revealDeadline: bigint;
    completionDeadline: bigint;
    zkProofHash: string;
    publicMetadata: string;
    revealer: string;
    revealedAt: bigint;
  };
}

export interface ZKPrivateEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMPLETION_WINDOW"
      | "MIN_AMOUNT"
      | "REVEAL_WINDOW"
      | "authorizeViewer"
      | "authorizedViewers"
      | "cancelEscrow"
      | "commitEscrow"
      | "commitments"
      | "completeEscrow"
      | "deauthorizeViewer"
      | "disputeEvidence"
      | "disputeVotesAgainst"
      | "disputeVotesFor"
      | "escrowCount"
      | "escrows"
      | "fileDispute"
      | "getCommitmentStats"
      | "getEscrowDetails"
      | "getPublicEscrowInfo"
      | "getUserEscrows"
      | "hasVotedOnDispute"
      | "isNullifierUsed"
      | "owner"
      | "revealEscrow"
      | "setVerifierContract"
      | "submitZKProof"
      | "usedCommitments"
      | "usedNullifiers"
      | "verifierContract"
      | "verifyCommitment"
      | "voteOnDispute"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeFiled"
      | "EscrowCancelled"
      | "EscrowCommitted"
      | "EscrowCompleted"
      | "EscrowRevealed"
      | "ZKProofSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMPLETION_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVEAL_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeViewer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedViewers",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitEscrow",
    values: [BytesLike, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeEscrow",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deauthorizeViewer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeEvidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeVotesAgainst",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeVotesFor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fileDispute",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitmentStats",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrowDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicEscrowInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEscrows",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVotedOnDispute",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNullifierUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revealEscrow",
    values: [BigNumberish, AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifierContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitZKProof",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedCommitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNullifiers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifierContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCommitment",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnDispute",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "COMPLETION_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_AMOUNT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REVEAL_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeViewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedViewers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deauthorizeViewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeVotesAgainst",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeVotesFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fileDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitmentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEscrowDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicEscrowInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasVotedOnDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifierContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitZKProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedNullifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifierContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteOnDispute",
    data: BytesLike
  ): Result;
}

export namespace DisputeFiledEvent {
  export type InputTuple = [escrowId: BigNumberish, reason: string];
  export type OutputTuple = [escrowId: bigint, reason: string];
  export interface OutputObject {
    escrowId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCancelledEvent {
  export type InputTuple = [escrowId: BigNumberish, refundAmount: BigNumberish];
  export type OutputTuple = [escrowId: bigint, refundAmount: bigint];
  export interface OutputObject {
    escrowId: bigint;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCommittedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    commitmentHash: BytesLike,
    privacyLevel: BigNumberish,
    revealDeadline: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: bigint,
    commitmentHash: string,
    privacyLevel: bigint,
    revealDeadline: bigint
  ];
  export interface OutputObject {
    escrowId: bigint;
    commitmentHash: string;
    privacyLevel: bigint;
    revealDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCompletedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    seller: AddressLike,
    amount: BigNumberish,
    nullifier: BytesLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    seller: string,
    amount: bigint,
    nullifier: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    seller: string;
    amount: bigint;
    nullifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRevealedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    seller: AddressLike,
    amount: BigNumberish,
    revealer: AddressLike
  ];
  export type OutputTuple = [
    escrowId: bigint,
    seller: string,
    amount: bigint,
    revealer: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    seller: string;
    amount: bigint;
    revealer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ZKProofSubmittedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    proofHash: BytesLike,
    verified: boolean
  ];
  export type OutputTuple = [
    escrowId: bigint,
    proofHash: string,
    verified: boolean
  ];
  export interface OutputObject {
    escrowId: bigint;
    proofHash: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZKPrivateEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ZKPrivateEscrow;
  waitForDeployment(): Promise<this>;

  interface: ZKPrivateEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMPLETION_WINDOW: TypedContractMethod<[], [bigint], "view">;

  MIN_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  REVEAL_WINDOW: TypedContractMethod<[], [bigint], "view">;

  authorizeViewer: TypedContractMethod<
    [_escrowId: BigNumberish, _viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedViewers: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  cancelEscrow: TypedContractMethod<
    [_escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  commitEscrow: TypedContractMethod<
    [
      _commitmentHash: BytesLike,
      _nullifier: BytesLike,
      _privacyLevel: BigNumberish,
      _publicMetadata: string
    ],
    [void],
    "payable"
  >;

  commitments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint] & {
        sellerHash: string;
        amountHash: string;
        nullifier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  completeEscrow: TypedContractMethod<
    [_escrowId: BigNumberish, _secret: BytesLike, _nullifier: BytesLike],
    [void],
    "nonpayable"
  >;

  deauthorizeViewer: TypedContractMethod<
    [_escrowId: BigNumberish, _viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  disputeEvidence: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  disputeVotesAgainst: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  disputeVotesFor: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  escrowCount: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        id: bigint;
        commitmentHash: string;
        seller: string;
        amount: bigint;
        privacyLevel: bigint;
        status: bigint;
        createdAt: bigint;
        revealDeadline: bigint;
        completionDeadline: bigint;
        zkProofHash: string;
        publicMetadata: string;
        revealer: string;
        revealedAt: bigint;
      }
    ],
    "view"
  >;

  fileDispute: TypedContractMethod<
    [_escrowId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;

  getCommitmentStats: TypedContractMethod<
    [_commitmentHash: BytesLike],
    [
      [boolean, string, bigint] & {
        isUsed: boolean;
        nullifier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEscrowDetails: TypedContractMethod<
    [_escrowId: BigNumberish],
    [ZKPrivateEscrow.PrivateEscrowStructOutput],
    "view"
  >;

  getPublicEscrowInfo: TypedContractMethod<
    [_escrowId: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, string] & {
        id: bigint;
        commitmentHash: string;
        privacyLevel: bigint;
        status: bigint;
        createdAt: bigint;
        revealDeadline: bigint;
        publicMetadata: string;
      }
    ],
    "view"
  >;

  getUserEscrows: TypedContractMethod<
    [_user: AddressLike, _status: BigNumberish],
    [bigint[]],
    "view"
  >;

  hasVotedOnDispute: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isNullifierUsed: TypedContractMethod<
    [_nullifier: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  revealEscrow: TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _seller: AddressLike,
      _secret: BytesLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setVerifierContract: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  submitZKProof: TypedContractMethod<
    [_escrowId: BigNumberish, _proofHash: BytesLike, _proof: BytesLike],
    [void],
    "nonpayable"
  >;

  usedCommitments: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  usedNullifiers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifierContract: TypedContractMethod<[], [string], "view">;

  verifyCommitment: TypedContractMethod<
    [
      _commitmentHash: BytesLike,
      _seller: AddressLike,
      _amount: BigNumberish,
      _secret: BytesLike
    ],
    [boolean],
    "view"
  >;

  voteOnDispute: TypedContractMethod<
    [_escrowId: BigNumberish, _approve: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMPLETION_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REVEAL_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "authorizeViewer"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _viewer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedViewers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelEscrow"
  ): TypedContractMethod<[_escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitEscrow"
  ): TypedContractMethod<
    [
      _commitmentHash: BytesLike,
      _nullifier: BytesLike,
      _privacyLevel: BigNumberish,
      _publicMetadata: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint] & {
        sellerHash: string;
        amountHash: string;
        nullifier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeEscrow"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _secret: BytesLike, _nullifier: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deauthorizeViewer"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _viewer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeEvidence"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "disputeVotesAgainst"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputeVotesFor"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        id: bigint;
        commitmentHash: string;
        seller: string;
        amount: bigint;
        privacyLevel: bigint;
        status: bigint;
        createdAt: bigint;
        revealDeadline: bigint;
        completionDeadline: bigint;
        zkProofHash: string;
        publicMetadata: string;
        revealer: string;
        revealedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fileDispute"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCommitmentStats"
  ): TypedContractMethod<
    [_commitmentHash: BytesLike],
    [
      [boolean, string, bigint] & {
        isUsed: boolean;
        nullifier: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrowDetails"
  ): TypedContractMethod<
    [_escrowId: BigNumberish],
    [ZKPrivateEscrow.PrivateEscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPublicEscrowInfo"
  ): TypedContractMethod<
    [_escrowId: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, string] & {
        id: bigint;
        commitmentHash: string;
        privacyLevel: bigint;
        status: bigint;
        createdAt: bigint;
        revealDeadline: bigint;
        publicMetadata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserEscrows"
  ): TypedContractMethod<
    [_user: AddressLike, _status: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVotedOnDispute"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isNullifierUsed"
  ): TypedContractMethod<[_nullifier: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revealEscrow"
  ): TypedContractMethod<
    [
      _escrowId: BigNumberish,
      _seller: AddressLike,
      _secret: BytesLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVerifierContract"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitZKProof"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _proofHash: BytesLike, _proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usedCommitments"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "usedNullifiers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifierContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyCommitment"
  ): TypedContractMethod<
    [
      _commitmentHash: BytesLike,
      _seller: AddressLike,
      _amount: BigNumberish,
      _secret: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "voteOnDispute"
  ): TypedContractMethod<
    [_escrowId: BigNumberish, _approve: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DisputeFiled"
  ): TypedContractEvent<
    DisputeFiledEvent.InputTuple,
    DisputeFiledEvent.OutputTuple,
    DisputeFiledEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCancelled"
  ): TypedContractEvent<
    EscrowCancelledEvent.InputTuple,
    EscrowCancelledEvent.OutputTuple,
    EscrowCancelledEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCommitted"
  ): TypedContractEvent<
    EscrowCommittedEvent.InputTuple,
    EscrowCommittedEvent.OutputTuple,
    EscrowCommittedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCompleted"
  ): TypedContractEvent<
    EscrowCompletedEvent.InputTuple,
    EscrowCompletedEvent.OutputTuple,
    EscrowCompletedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRevealed"
  ): TypedContractEvent<
    EscrowRevealedEvent.InputTuple,
    EscrowRevealedEvent.OutputTuple,
    EscrowRevealedEvent.OutputObject
  >;
  getEvent(
    key: "ZKProofSubmitted"
  ): TypedContractEvent<
    ZKProofSubmittedEvent.InputTuple,
    ZKProofSubmittedEvent.OutputTuple,
    ZKProofSubmittedEvent.OutputObject
  >;

  filters: {
    "DisputeFiled(uint256,string)": TypedContractEvent<
      DisputeFiledEvent.InputTuple,
      DisputeFiledEvent.OutputTuple,
      DisputeFiledEvent.OutputObject
    >;
    DisputeFiled: TypedContractEvent<
      DisputeFiledEvent.InputTuple,
      DisputeFiledEvent.OutputTuple,
      DisputeFiledEvent.OutputObject
    >;

    "EscrowCancelled(uint256,uint256)": TypedContractEvent<
      EscrowCancelledEvent.InputTuple,
      EscrowCancelledEvent.OutputTuple,
      EscrowCancelledEvent.OutputObject
    >;
    EscrowCancelled: TypedContractEvent<
      EscrowCancelledEvent.InputTuple,
      EscrowCancelledEvent.OutputTuple,
      EscrowCancelledEvent.OutputObject
    >;

    "EscrowCommitted(uint256,bytes32,uint8,uint256)": TypedContractEvent<
      EscrowCommittedEvent.InputTuple,
      EscrowCommittedEvent.OutputTuple,
      EscrowCommittedEvent.OutputObject
    >;
    EscrowCommitted: TypedContractEvent<
      EscrowCommittedEvent.InputTuple,
      EscrowCommittedEvent.OutputTuple,
      EscrowCommittedEvent.OutputObject
    >;

    "EscrowCompleted(uint256,address,uint256,bytes32)": TypedContractEvent<
      EscrowCompletedEvent.InputTuple,
      EscrowCompletedEvent.OutputTuple,
      EscrowCompletedEvent.OutputObject
    >;
    EscrowCompleted: TypedContractEvent<
      EscrowCompletedEvent.InputTuple,
      EscrowCompletedEvent.OutputTuple,
      EscrowCompletedEvent.OutputObject
    >;

    "EscrowRevealed(uint256,address,uint256,address)": TypedContractEvent<
      EscrowRevealedEvent.InputTuple,
      EscrowRevealedEvent.OutputTuple,
      EscrowRevealedEvent.OutputObject
    >;
    EscrowRevealed: TypedContractEvent<
      EscrowRevealedEvent.InputTuple,
      EscrowRevealedEvent.OutputTuple,
      EscrowRevealedEvent.OutputObject
    >;

    "ZKProofSubmitted(uint256,bytes32,bool)": TypedContractEvent<
      ZKProofSubmittedEvent.InputTuple,
      ZKProofSubmittedEvent.OutputTuple,
      ZKProofSubmittedEvent.OutputObject
    >;
    ZKProofSubmitted: TypedContractEvent<
      ZKProofSubmittedEvent.InputTuple,
      ZKProofSubmittedEvent.OutputTuple,
      ZKProofSubmittedEvent.OutputObject
    >;
  };
}
